import React, { createContext, useContext, useState } from 'react';

export const translations: any = {
  EN: {
    trade: 'Trade',
    connectWallet: 'Connect Wallet',
    swap: 'Swap',
    send: 'Send',
    to: 'To',
    limit: 'Limit',
    pay: 'Pay',
    receive: 'Receive',
    balance: 'Balance:',
    settings: 'Settings',
    max: 'Max',
    enterAmount: 'Enter an amount',
    insufficient: 'Insufficient ',
    swapSubtitle: 'Buy and sell any token',
    limitSubtitle: 'Trade at a specified price',
    sendSubtitle: 'Transfer tokens to anyone',
    docs: 'Documentation',
    earn: 'Earn',
    referrals: 'Referrals',
    portfolio: 'Portfolio',
    languages: 'Languages',
    networks: 'Networks',
    averagePrice: 'Average Price',
    priceImpact: 'Price Impact',
    isWorth: 'is worth',
    When: 'When',
    enterRecipient: 'Enter a recipient',
    enterWalletAddress: 'Enter wallet address',
    market: 'Market',
    Warning: 'Warning: High price impact! Your trade will move the market price by more than 5%',
    markets: 'Market',
    type: 'Type',
    size: 'Size',
    price: 'Price',
    amountFilled: 'Amount Filled',
    active: 'Active',
    time: 'Time',
    view: 'View',
    amount: 'Amount',
    all: 'All',
    buy: 'Buy',
    sell: 'Sell',
    noOpenOrders: 'No orders currently active',
    noTradeHistory: 'No trade history',
    noOrderHistory: 'No order history',
    cancelAll: 'Cancel All',
    openOrders: 'Open Orders',
    tradeHistory: 'Trade History',
    orderHistory: 'Order History',
    no: 'No',
    yes: 'Yes',
    total: 'Total',
    Spread: 'Spread',
    orderbook: 'Order Book',
    trades: 'Trades',
    availableLiquidity: 'Available Liquidity',
    dayVolume: '24hr Volume',
    dayHigh: '24hr High',
    dayLow: '24hr Low',
    dayChange: '24hr Change',
    selectAToken: 'Select a Token',
    selectTokenSubtitle: 'Select a token from our default list or find one by searching for its symbol or address.',
    searchToken: 'Search by symbol or address',
    slippage: 'Max Slippage',
    partialFill: 'Partial Fill',
    assets: 'Assets',
    USDvalue: 'USD Value',
    noWallet: "Don't have a wallet?",
    createWallet: ' Create One',
    totalAccountValue: 'Total Account Value',
    totalVolume: '24hr Volume',
    tradeValue: 'Trade Value',
    filled: 'Filled',
    canceled: 'Canceled',
    status: 'Status',
    mid: 'Mid',
    placeOrder: 'Place Order',
    avgPrice: 'Avg. Price',
    connectWalletSubtitle: 'Connect your wallet to start trading.',
    success: 'Success',
    viewOnExplorer: 'View on Explorer',
    online: 'ONLINE',
    offline: 'OFFLINE',
    twitter: 'Twitter',
    discord: 'Discord',
    beta: 'Beta',
    installed: 'Installed',
    popular: 'Popular',
    chart: 'Chart',
    copied: 'Copied',
    copyTokenAddress: 'Copy token address',
    clickCopyAddress: 'Click to copy address',
    visitTokenWebsite: 'Visit token website',
    copy: 'Copy',
    actions: 'Actions',
    graphConnectWallet: 'Connect your wallet to view your portfolio.',
    noTokensDetected: 'No tokens detected',
    performance: 'PERFORMANCE',
    balances: 'Balances',
    welcome: 'Welcome',
    portfolioValue: 'Portfolio Value',
    approve: 'Approve',
    wrap: 'Wrap',
    unwrap: 'Unwrap',
    useMarket: 'Use Market',
    onlyCurrentMarket: 'Only this market',
    limitSettings: 'Limit Settings',
    swapSettings: 'Swap Settings',
    left: 'Left',
    right: 'Right',
    customizableSubtitle: 'Customize your trading experience.',
    tradePanelPosition: 'Trade Panel Position',
    orderbookPosition: 'Orderbook Position',
    side: 'Side',
    panel: 'Panel',
    revertToDefault: 'Revert to Default',
    language: 'Language',
    referralSettings: 'Referral Settings',
    changeusedref: 'Change Used Referral',
    setRef: 'Set Referral',
    createOrViewRefLink: 'Create or View Referral Link',
    yourreflink: 'Your Referral Link',
    copyLink: 'Copy Link',
    earnings: 'Earnings',
    totalfees: 'Total Fees',
    nothingtoclaim: 'Nothing to Claim',
    claimfees: 'Claim Fees',
    simpleView: 'Simple View',
    amountFilledSubtitle: 'The amount of tokens that have been filled for this order',
    tradeValueSubtitle: 'The total value of your trade',
    statusSubtitle: 'The fill status of this order',
    signTransaction: 'Sign Transaction',
    addLiquidityOnly: 'Add Liquidity Only',
    addLiquidityOnlySubtitle: 'If enabled, ensure this order is added to the book as a maker order',
    claimTitle: 'Claim Your Earnings',
    totalClaim: 'Total Claimable',
    shareEarn: 'Share & Earn',
    customize: 'Customize',
    create: 'Create',
    noLink: 'Create a referral link to start earning!',
    communityRewards: 'Community Rewards',
    communityRewardsText: 'Earn a 25% commission and give your referred users a 25% fee discount',
    instantTracking: 'Instant Tracking',
    instantTrackingText: 'Earnings from the referral program are available to claim instantly',
    tierBenefits: 'Incentive Multipliers',
    tierBenefitsText: 'Both you and your referred users will earn more rewards',
    usingCode: 'Using Code:',
    enteracode: 'Enter referral code',
    earningsDashboard: 'Earnings Dashboard',
    earningsSubtitle: 'Track and claim your referral rewards',
    totalClaimable: 'Total Claimable',
    tokenBreakdown: 'Token Breakdown',
    availableToClaim: 'Available to claim',
    referralsHelp: 'Claim your earned fees from the referral program. Fees are collected in the token they were paid in and can be claimed anytime.',
    learnMore: 'Learn More',
    noSelfRefer: 'You cannot use your own referral code',
    customizeWarning: 'If you change your custom link, the previous one will stop working.',
    createWarning: 'Create a custom referral link',
    referralSubtitle: "Get a 25% fee discount when you use a friend or creator's referral code!",
    yourLink: 'Your referral link:',
    createCode: 'Create referral code',
    signTxn: 'Sign Transaction',
    getHelp: 'Get Help',
    totalVol: 'Total Volume',
    activeOrders: 'Active Orders',
    details: 'Details',
    account: 'ACCOUNT',
    accountSubtitle: "Overview of your wallet's recent activity",
    toggle: 'Toggle visibility of numbers',
    day: '24h',
    week: '1w',
    weektwo: '2w',
    month: '1mo',
    past: 'past',
    portValue: 'Portfolio Value',
    slippageHelp: 'The maximum percentage difference between the expected and executed price of this trade',
    averagePriceHelp: 'The estimated average execution price for this trade',
    priceImpactHelp: 'The estimated change in market price caused by this trade',
    nofeeforwrap: 'Wrapping and unwrapping ETH is 1:1 and does not incur any fees',
    takerfeeexplanation: 'Taker orders pay a small fee',
    makerfeeexplanation: 'Maker orders are not charged any fee',
    fee: 'Fee',
    cancel: 'Cancel',
    switchto: 'Switch to',
    insufficientLiquidity: 'Insufficient Liquidity',
    insufficientLiquidityWarning: 'Warning: Insufficient liquidity. Try splitting this trade into multiple smaller orders or enabling partial fill',
    insufficientLiquidityWarningMultihop: 'Warning: Insufficient liquidity. Try splitting this trade into multiple smaller orders',
    priceOutOfRangeBuy: 'Post only price too high',
    priceOutOfRangeSell: 'Post only price too low',
    clearRef: 'Clear Referral Code',
    comingSoon: 'Coming Soon...',
    earnDesc: "We're working hard to bring you new ways to earn with your crypto. Stay tuned for updates!",
    showOB: 'Show Order Book',
    showOC: 'Show Order Center',
    priceOutOfRangeWarningBuy: 'Warning: Limit price higher than lowest ask price. This trade will likely execute as a taker order',
    priceOutOfRangeWarningSell: 'Warning: Limit price lower than highest bid price. This trade will likely execute as a taker order',
    limitPrice: 'Limit Price',
    limitPriceSubtitle: 'The price at which your order is set to execute',
    partialFillSubtitle: 'If enabled, allow partial execution if slippage is exceeded',
    sHigh: 'Session High',
    sLow: 'Session Low',
    hideBalances: 'Hide Balances',
    disconnect: 'Disconnect',
    tradingStats: 'TRADING STATS',
    refStats: 'REFERRAL STATS',
    claimableRewards: 'Claimable Rewards',
    myCode: 'My Code:',
    noCode: "Don't have a code? Create one",
    bal: 'Balance',
    website: 'Website',
    terms: 'Terms of Use',
    view_documentation: 'Learn about Crystal',
    visit_homepage: "Visit Crystal's website",
    read_terms: 'Legal terms and conditions',
    join_community: "Join Crystal's community",
    follow_updates: "Follow Crystal's updates",
    more: 'More',
    onlyCurrentMarketHelp: 'Only display orders for this market',
    swapComplete: 'Swap Complete',
    limitComplete: 'Limit Order Complete',
    sendComplete: 'Send Complete',
    limitCancelled: 'Limit Order Cancelled',
    fillComplete: 'Order Filled',
    wrapComplete: 'Wrap Complete',
    unwrapComplete: 'Unwrap Complete',
    approveComplete: 'Approval Complete',
    basic: 'BASIC',
    pro: 'Pro',
    searchMarkets: 'Search Markets',
    clear: 'Clear',
    volume: 'Volume',
    byConnecting: "By connecting a wallet, you agree to Crystal's",
    termsOfService: 'Terms of Service',
    andConsentTo: 'and consent to its',
    privacyPolicy: 'Privacy Policy',
    enterReferralCode: 'Enter Referral Code',
    setReferral: 'Set Referral',
    clearReferralLink: 'Clear Referral Code',
    codeTaken: 'Code taken',
    invalid: 'Invalid',
    requestingConnection: 'Requesting Connection',
    confirmConnection1: 'Confirm the connection in the',
    confirmConnection2: 'browser extension to continue',
    lessThanMinSize: 'Limit order size must be >1 USDC',
    enterLimitPrice: 'Enter a limit price',
    advancedView: 'Advanced View',
    basicView: 'Basic View',
    advancedViewText: 'Master the markets',
    basicViewText: 'Trade with ease',
    noTokens: 'No tokens found',
    noMarkets: 'No markets found',
    toNavigate: 'to navigate',
    toSelect: 'to select',
    toClose: 'to close',
    pleaseEnterCode: 'Please enter a referral code',
    transactionHistory: 'Transaction History',
    search: 'Search',
    minimumSize: 'Minimum Size',
    enableFilter: 'Enable Filter',
    last: 'Last',
    scale: 'Scale',
    noTransactionsYet: 'No transactions yet',
    filledAt: 'filled at',
    start: 'Start',
    end: 'End',
    skew: 'Skew',
    orders: 'Orders',
    enterStartPrice: 'Enter a start price',
    enterEndPrice: 'Enter an end price',
    startPriceHigh: 'Start price too high',
    startPriceLow: 'Start price too low',
    endPriceHigh: 'End price too high',
    endPriceLow: 'End price too low',
    scaleMinSize: 'Smallest order size must be >1 USDC',
    enterOrders: 'Enter order count',
    enterSkew: 'Enter size skew',
    transactionDetails: 'Transaction Details',
    swapDetails: 'Swap Details',
    limitOrderDetails: 'Limit Order Details',
    sendDetails: 'Send Details',
    cancelDetails: 'Cancellation Details',
    fillDetails: 'Fill Details',
    wrapDetails: 'Wrap Details',
    unwrapDetails: 'Unwrap Details',
    approveDetails: 'Approval Details',
    generalInfo: 'Transaction Information',
    txType: 'Tx Type',
    txTime: 'Tx Time',
    txHash: 'Tx Hash',
    tokenInfo: 'Token Information',
    fromToken: 'Input Token',
    toToken: 'Output Token',
    recipientInfo: 'Recipient Information',
    contractInfo: 'Contract Information',
    address: 'Address',
    token: 'Token',
    feeInfo: 'Fee Information',
    gasUsed: 'Gas Used',
    gasPrice: 'Gas Price',
    totalFee: 'Total Fee',
    back: 'Back',
    at: 'at',
    leaderboard: 'Leaderboard',
    orderType: 'Order Type',
    editAccountTitle: "Edit Account",
    editAccountSubtitle: "Change your username and profile photo",
    username: "Username",
    chooseNewPhoto: "Choose New Photo",
    saveChanges: "Save Changes",
    viewRules: "View Rules",
    earned: "Earned",
    rank: "Rank",
    editAccount: "Edit Account",
    createAccount: "Create Account",
    user: "User",
    totalXP: "Total XP",
    choosePhoto: "Choose Photo",
    next: "Next",
    skip: "Skip",
    complete: "Complete",
    challengeOverview: "Introducing Crystals: Season 0",
    learnHowToCompete: "Compete to earn Crystals",
    precisionMatters: "Place Limit Orders",
    placeYourBids: "Place your limit orders near the mid price. The closer, the better.",
    earnCrystals: "Earn Crystals",
    midsGiveYou: "Recieve Crystals as your order provides liquidity.",
    claimRewards: "Recieve Rewards",
    competeOnLeaderboards: "Climb the leaderboard and earn yourself a share of future protocol ownership.",
    continueAsGuest: "Continue as Guest",
    getStarted: "Get Started",
    of: "of",
    page: "Page",
    viewYourPosition: "View Your Position",
    mint: "Mint",
    limitFailed: 'Limit Order Failed',
    sendFailed: 'Send Transaction Failed',
    sendingTransaction: 'Sending Transaction',
    swapFailed: 'Swap Transaction Failed',
    swapFailedDetails: 'Swap Failure Details',
    sendFailedDetails: 'Send Failure Details',
    limitFailedDetails: 'Limit Failure Details',
    failed: 'Failed',
    errorInfo: 'Error Information',
    attemptedSwap: 'Attempted Swap',
    attemptedSend: 'Attempted Send',
    sendTo: 'Send to',
    done: 'Done',
    deposit: 'Deposit',
    depositWarning: "Your deposit must be sent on the Monad network. Your wallet is self-custodial; Crystal cannot access your funds.",
    audioNotifications: "Enable Audio Notifications",
    connectYourWallet: "Connect Your Wallet",
    connectYourWalletSubtitle: "Connect your wallet to view the leaderboard",
    searchAMarket: "Search for a market",
    browsePairs: "Browse trading pairs",
    custom: "Custom",
    confirmSwap: "Confirm Swap",
    highPriceImpactMessage: "Warning! High Price Impact! Your trade will move the market price more than 5%",
    showTradeMarkers: "Show Trade Markers",
    usersReferred: "Users Referred",
    editUsername: "Edit Username",
    bonusCommission: "Bonus Commission",
    editUsernameSubtitle: "This username will be visible on the leaderboard to all.",
    yourWalletAddress: "Your Wallet Address",
    usernameAlreadyTaken: "Username already taken",
    minUsernameLength: "Username must be at least 3 characters",
    usernameFilter: "Username can only contain letters, numbers, and underscores",
    maxUsernameLength: "Username must be less than 20 characters",
    showChartOrders: "Show Chart Orders",
    bonusCommision: "Bonus Commission",
    edit: "Edit",
    shareEarnText: "Share your referral link with friends and earn 25% of their fees.",
    totalUsersReferred: "Total Users Referred",
    scaleTooltip: "Place multiple limit orders between a specified price range in a single transaction",
    setRefFailed: "Invalid referral code",
    favorites: "Favorites",
    lsts: "LSTs",
    stablecoins: "Stablecoins",
    memes: "Memes",
    pointMultiplier: "Point Multiplier",
    crystalsFromReferrals: "Crystals From Referrals",
    refAd: "Save on fees and earn extra rewards through the referral program",
    monadDesc: "The native token of the Monad blockchain, an innovative high performance EVM network supporting over 10,000 TPS.",
    wMonDesc: "An ERC-20 wrapper of Monad's native token (MON) for greater compatibility with smart contracts.",
    wethDesc: "An ERC-20 wrapper of Ethereum's native token (ETH) for greater compatiblity with smart contracts.",
    wbtcDesc: "An ERC-20 wrapper of Bitcoin on the Monad network.",
    wsolDesc: "An ERC-20 wrapper of Solana's native token (SOL) for greater compatiblity with smart contracts.",
    usdtDesc: "The world's most widely-used stablecoin, pegged to the US Dollar at a 1:1 ratio.",
    smonDesc: "sMON is Kintsu’s Liquid Staking Token on Monad, DAO-aligned, and designed to let users earn staking rewards while staying composable across the ecosystem.",
    aprmonDesc: "MEV Powered Monad Liquid Staking by aPriori",
    shmonDesc: "shMON: The world's first Holistic Liquid Staking Token with the best staking rewards on Monad.",
    dakDesc: "Known for courage and tradition, Molandak is home to the brave-hearted who rip challenges head-on.",
    chogDesc: "Chog is the house for the wise and industrious who value intellect, strategy, and tireless work ethic.",
    yakiDesc: "Moyaki swims for those who rise from humble beginnings with an unyielding drive to succeed.",
    mintDesc: "An exclusive commemorative NFT for our earliest testnet users. Missed it? Another drop is coming, with eligibility based on leaderboard ranking.",
    mintTitle: "Mint NFT",
    mintSubtitle: "Create your exclusive digital collectible",
    mintCount: "Mints",
    holders: "Holders",
    eligible: "Eligible",
    minted: "Minted",
    free: "Free",
    minting: "Minting...",
    showChartOutliers: "Show Chart Outliers",
    alreadyMinted: "Already Minted",
    notEligible: "Not Eligible",
    loading: "Loading...",
  },
  CN: {
    trade: "交易",
    connectWallet: "连接钱包",
    swap: "兑换",
    send: "发送",
    to: "至",
    limit: "限价",
    pay: "支付",
    receive: "接收",
    balance: "余额：",
    settings: "设置",
    max: "最大",
    enterAmount: "输入金额",
    insufficient: "余额不足 ",
    swapSubtitle: "买卖任何代币",
    limitSubtitle: "在指定价格交易",
    sendSubtitle: "向任何人转账代币",
    docs: "文档",
    earn: "赚取",
    referrals: "推荐",
    portfolio: "投资组合",
    languages: "语言",
    networks: "网络",
    averagePrice: "平均价格",
    priceImpact: "价格影响",
    isWorth: "价值",
    When: "当",
    enterRecipient: "输入接收者",
    enterWalletAddress: "输入钱包地址",
    market: "市场",
    Warning: "警告：高价格影响！您的交易将使市场价格变动超过5%",
    markets: "市场",
    type: "类型",
    size: "规模",
    price: "价格",
    amountFilled: "已成交金额",
    active: "活跃",
    time: "时间",
    view: "查看",
    amount: "金额",
    all: "全部",
    buy: "买入",
    sell: "卖出",
    noOpenOrders: "当前没有活跃订单",
    noTradeHistory: "无交易历史",
    noOrderHistory: "无订单历史",
    cancelAll: "取消全部",
    openOrders: "未成交订单",
    tradeHistory: "交易历史",
    orderHistory: "订单历史",
    no: "否",
    yes: "是",
    total: "总计",
    Spread: "价差",
    orderbook: "订单簿",
    trades: "交易",
    availableLiquidity: "可用流动性",
    dayVolume: "24小时交易量",
    dayHigh: "24小时最高价",
    dayLow: "24小时最低价",
    dayChange: "24小时涨跌幅",
    selectAToken: "选择代币",
    selectTokenSubtitle: "从我们的默认列表中选择代币，或通过搜索其符号或地址查找。",
    searchToken: "按符号或地址搜索",
    slippage: "最大滑点",
    partialFill: "部分成交",
    assets: "资产",
    USDvalue: "美元价值",
    noWallet: "没有钱包？",
    createWallet: " 创建一个",
    totalAccountValue: "账户总价值",
    totalVolume: "24小时交易量",
    tradeValue: "交易价值",
    filled: "已成交",
    canceled: "已取消",
    status: "状态",
    mid: "中间价",
    placeOrder: "下单",
    avgPrice: "平均价格",
    connectWalletSubtitle: "连接您的钱包开始交易。",
    success: "成功",
    viewOnExplorer: "在区块浏览器查看",
    online: "在线",
    offline: "离线",
    twitter: "推特",
    discord: "Discord",
    beta: "测试版",
    installed: "已安装",
    popular: "热门",
    chart: "图表",
    copied: "已复制",
    copyTokenAddress: "复制代币地址",
    clickCopyAddress: "点击复制地址",
    visitTokenWebsite: "访问代币网站",
    copy: "复制",
    actions: "操作",
    graphConnectWallet: "连接钱包查看您的投资组合。",
    noTokensDetected: "未检测到代币",
    performance: "表现",
    balances: "余额",
    welcome: "欢迎",
    portfolioValue: "投资组合价值",
    approve: "授权",
    wrap: "包装",
    unwrap: "解包",
    useMarket: "使用市场",
    onlyCurrentMarket: "仅当前市场",
    limitSettings: "限价设置",
    swapSettings: "兑换设置",
    left: "左",
    right: "右",
    customizableSubtitle: "自定义您的交易体验。",
    tradePanelPosition: "交易面板位置",
    orderbookPosition: "订单簿位置",
    side: "侧边",
    panel: "面板",
    revertToDefault: "恢复默认",
    language: "语言",
    referralSettings: "推荐设置",
    changeusedref: "更改使用的推荐码",
    setRef: "设置推荐",
    createOrViewRefLink: "创建或查看推荐链接",
    yourreflink: "您的推荐链接",
    copyLink: "复制链接",
    earnings: "收益",
    totalfees: "总费用",
    nothingtoclaim: "没有可领取的",
    claimfees: "领取费用",
    simpleView: "简洁视图",
    amountFilledSubtitle: "此订单已成交的代币数量",
    tradeValueSubtitle: "您交易的总价值",
    statusSubtitle: "此订单的成交状态",
    signTransaction: "签署交易",
    addLiquidityOnly: "仅添加流动性",
    addLiquidityOnlySubtitle: "如果启用，确保此订单作为做市商订单添加到订单簿",
    claimTitle: "领取您的收益",
    totalClaim: "总可领取",
    shareEarn: "分享并赚取",
    customize: "自定义",
    create: "创建",
    noLink: "创建推荐链接开始赚钱！",
    communityRewards: "社区奖励",
    communityRewardsText: "赚取25%的佣金并给您推荐的用户25%的费用折扣",
    instantTracking: "即时跟踪",
    instantTrackingText: "推荐计划的收益可以立即领取",
    tierBenefits: "奖励倍数",
    tierBenefitsText: "您和您推荐的用户都将获得更多奖励",
    usingCode: "使用代码：",
    enteracode: "输入推荐码",
    earningsDashboard: "收益仪表板",
    earningsSubtitle: "跟踪并领取您的推荐奖励",
    totalClaimable: "总可领取",
    tokenBreakdown: "代币明细",
    availableToClaim: "可领取",
    referralsHelp: "领取您从推荐计划中赚取的费用。费用以支付的代币收集，可随时领取。",
    learnMore: "了解更多",
    noSelfRefer: "您不能使用自己的推荐码",
    customizeWarning: "如果您更改自定义链接，之前的链接将停止工作。",
    createWarning: "创建自定义推荐链接",
    referralSubtitle: "使用朋友或创作者的推荐码获得25%的费用折扣！",
    yourLink: "您的推荐链接：",
    createCode: "创建推荐码",
    signTxn: "签署交易",
    getHelp: "获取帮助",
    totalVol: "总交易量",
    activeOrders: "活跃订单",
    details: "详情",
    account: "账户",
    accountSubtitle: "您钱包最近活动的概览",
    toggle: "切换数字可见性",
    day: "24小时",
    week: "1周",
    weektwo: "2周",
    month: "1个月",
    past: "过去",
    portValue: "投资组合价值",
    slippageHelp: "此交易预期价格与执行价格之间的最大百分比差异",
    averagePriceHelp: "此交易的估计平均执行价格",
    priceImpactHelp: "此交易引起的市场价格估计变化",
    nofeeforwrap: "包装和解包ETH是1:1的，不产生任何费用",
    takerfeeexplanation: "吃单需支付小额费用",
    makerfeeexplanation: "挂单不收取任何费用",
    fee: "费用",
    cancel: "取消",
    switchto: "切换到",
    insufficientLiquidity: "流动性不足",
    insufficientLiquidityWarning: "警告：流动性不足。尝试将此交易分成多个较小的订单或启用部分成交",
    insufficientLiquidityWarningMultihop: "警告：流动性不足。尝试将此交易分成多个较小的订单",
    priceOutOfRangeBuy: "仅限挂单价格过高",
    priceOutOfRangeSell: "仅限挂单价格过低",
    clearRef: "清除推荐码",
    comingSoon: "即将推出...",
    earnDesc: "我们正在努力为您带来新的加密货币赚钱方式。敬请期待更新！",
    showOB: "显示订单簿",
    showOC: "显示订单中心",
    priceOutOfRangeWarningBuy: "警告：限价高于最低卖价。此交易可能作为吃单执行",
    priceOutOfRangeWarningSell: "警告：限价低于最高买价。此交易可能作为吃单执行",
    limitPrice: "限价",
    limitPriceSubtitle: "您的订单设置为执行的价格",
    partialFillSubtitle: "如果启用，当滑点超过时允许部分执行",
    sHigh: "会话最高价",
    sLow: "会话最低价",
    hideBalances: "隐藏余额",
    disconnect: "断开连接",
    tradingStats: "交易数据",
    refStats: "推荐数据",
    claimableRewards: "可领取奖励",
    myCode: "我的代码：",
    noCode: "没有代码？创建一个",
    bal: "余额",
    website: "网站",
    terms: "使用条款",
    view_documentation: "了解Crystal",
    visit_homepage: "访问Crystal网站",
    read_terms: "法律条款和条件",
    join_community: "加入Crystal社区",
    follow_updates: "关注Crystal更新",
    more: "更多",
    onlyCurrentMarketHelp: "仅显示此市场的订单",
    swapComplete: "兑换完成",
    limitComplete: "限价订单完成",
    sendComplete: "发送完成",
    limitCancelled: "限价订单已取消",
    fillComplete: "订单已成交",
    wrapComplete: "包装完成",
    unwrapComplete: "解包完成",
    approveComplete: "授权完成",
    basic: "基础",
    pro: "专业",
    searchMarkets: "搜索市场",
    clear: "清除",
    volume: "交易量",
    byConnecting: "通过连接钱包，您同意Crystal的",
    termsOfService: "服务条款",
    andConsentTo: "并同意其",
    privacyPolicy: "隐私政策",
    enterReferralCode: "输入推荐码",
    setReferral: "设置推荐",
    clearReferralLink: "清除推荐码",
    codeTaken: "代码已被占用",
    invalid: "无效",
    requestingConnection: "请求连接",
    confirmConnection1: "在浏览器扩展中确认",
    confirmConnection2: "连接以继续",
    lessThanMinSize: "限价订单规模必须 >1 USDC",
    enterLimitPrice: "输入限价",
    advancedView: "高级视图",
    basicView: "基础视图",
    advancedViewText: "掌控市场",
    basicViewText: "轻松交易",
    noTokens: "未找到代币",
    noMarkets: "未找到市场",
    toNavigate: "导航",
    toSelect: "选择",
    toClose: "关闭",
    pleaseEnterCode: "请输入推荐码",
    transactionHistory: "交易历史",
    search: "搜索",
    minimumSize: "最小规模",
    enableFilter: "启用过滤器",
    last: "最后",
    scale: "梯度",
    noTransactionsYet: "暂无交易",
    filledAt: "成交价",
    start: "起始",
    end: "结束",
    skew: "偏斜",
    orders: "订单",
    enterStartPrice: "输入起始价格",
    enterEndPrice: "输入结束价格",
    startPriceHigh: "起始价格过高",
    startPriceLow: "起始价格过低",
    endPriceHigh: "结束价格过高",
    endPriceLow: "结束价格过低",
    scaleMinSize: "最小订单规模必须 >1 USDC",
    enterOrders: "输入订单数量",
    enterSkew: "输入规模偏斜",
    transactionDetails: "交易详情",
    swapDetails: "兑换详情",
    limitOrderDetails: "限价订单详情",
    sendDetails: "发送详情",
    cancelDetails: "取消详情",
    fillDetails: "成交详情",
    wrapDetails: "包装详情",
    unwrapDetails: "解包详情",
    approveDetails: "授权详情",
    generalInfo: "交易信息",
    txType: "交易类型",
    txTime: "交易时间",
    txHash: "交易哈希",
    tokenInfo: "代币信息",
    fromToken: "输入代币",
    toToken: "输出代币",
    recipientInfo: "接收者信息",
    contractInfo: "合约信息",
    address: "地址",
    token: "代币",
    feeInfo: "费用信息",
    gasUsed: "使用的Gas",
    gasPrice: "Gas价格",
    totalFee: "总费用",
    back: "返回",
    at: "在",
    leaderboard: "排行榜",
    orderType: "订单类型",
    editAccountTitle: "编辑账户",
    editAccountSubtitle: "更改您的用户名和头像",
    username: "用户名",
    chooseNewPhoto: "选择新照片",
    saveChanges: "保存更改",
    viewRules: "查看规则",
    earned: "已赚取",
    rank: "排名",
    editAccount: "编辑账户",
    createAccount: "创建账户",
    user: "用户",
    totalXP: "总经验值",
    choosePhoto: "选择照片",
    next: "下一步",
    skip: "跳过",
    complete: "完成",
    challengeOverview: "介绍Crystal：第0季",
    learnHowToCompete: "竞争赚取Crystal",
    precisionMatters: "下限价订单",
    placeYourBids: "在中间价附近下限价订单。越接近越好。",
    earnCrystals: "赚取Crystal",
    midsGiveYou: "当您的订单提供流动性时获得Crystal。",
    claimRewards: "获取奖励",
    competeOnLeaderboards: "攀登排行榜，赢取未来协议所有权份额。",
    continueAsGuest: "以访客身份继续",
    getStarted: "开始使用",
    of: "的",
    page: "页",
    viewYourPosition: "查看您的位置",
    mint: "铸造",
    limitFailed: "限价订单失败",
    sendFailed: "发送交易失败",
    sendingTransaction: "发送交易中",
    swapFailed: "兑换交易失败",
    swapFailedDetails: "兑换失败详情",
    sendFailedDetails: "发送失败详情",
    limitFailedDetails: "限价失败详情",
    failed: "失败",
    errorInfo: "错误信息",
    attemptedSwap: "尝试兑换",
    attemptedSend: "尝试发送",
    sendTo: "发送至",
    done: "完成",
    deposit: "充值",
    depositWarning: "您的充值必须在Monad网络上发送。您的钱包是自托管的；Crystal无法访问您的资金。",
    audioNotifications: "启用音频通知",
    connectYourWallet: "连接您的钱包",
    connectYourWalletSubtitle: "连接您的钱包查看排行榜",
    searchAMarket: "搜索市场",
    browsePairs: "浏览交易对",
    custom: "自定义",
    confirmSwap: "确认兑换",
    highPriceImpactMessage: "警告！高价格影响！您的交易将使市场价格变动超过5%",
    showTradeMarkers: "显示交易标记",
    usersReferred: "已推荐用户",
    editUsername: "编辑用户名",
    bonusCommission: "额外佣金",
    editUsernameSubtitle: "此用户名将在排行榜上对所有人可见。",
    yourWalletAddress: "您的钱包地址",
    usernameAlreadyTaken: "用户名已被占用",
    minUsernameLength: "用户名至少需要3个字符",
    usernameFilter: "用户名只能包含字母、数字和下划线",
    maxUsernameLength: "用户名必须少于20个字符",
    showChartOrders: "显示图表订单",
    bonusCommision: "额外佣金",
    edit: "编辑",
    shareEarnText: "与朋友分享您的推荐链接，赚取他们25%的费用。",
    totalUsersReferred: "总推荐用户数",
    scaleTooltip: "在一次交易中在指定价格范围内下多个限价订单",
    setRefFailed: "设置推荐码失败，代码可能无效",
    favorites: "收藏",
    lsts: "LST代币",
    stablecoins: "稳定币",
    memes: "迷因币",
    pointMultiplier: "积分倍数",
    crystalsFromReferrals: "推荐获得的Crystal",
    refAd: "使用您的推荐码获得高达50%的所有费用返利",
    monadDesc: "Monad 区块链的原生代币，是一个创新的高性能 EVM 网络，支持超过 10,000 TPS。",
    wMonDesc: "Monad 原生代币（MON）的 ERC-20 封装版本，增强与智能合约的兼容性。",
    wethDesc: "以太坊原生代币（ETH）的 ERC-20 封装版本，增强与智能合约的兼容性。",
    wbtcDesc: "在 Monad 网络上的比特币 ERC-20 封装版本。",
    wsolDesc: "Solana 原生代币（SOL）的 ERC-20 封装版本，增强与智能合约的兼容性。",
    usdtDesc: "全球使用最广泛的稳定币，与美元 1:1 挂钩。",
    smonDesc: "sMON 是 Kintsu 推出的 Monad 上的流动质押代币，贴合 DAO 理念，让用户在参与生态的同时获得质押收益。",
    aprmonDesc: "aPriori 推出的 MEV 驱动 Monad 流动质押代币。",
    shmonDesc: "shMON：全球首个全链整合的流动质押代币，提供 Monad 上最优质的质押收益。",
    dakDesc: "Molandak 以勇气与传统著称，聚集了直面挑战、勇往直前的勇士。",
    chogDesc: "Chog 是睿智与勤奋者的聚集地，重视智慧、策略与不懈努力。",
    yakiDesc: "Moyaki 属于那些从平凡中崛起、始终不放弃追求成功的奋斗者。",
    mintDesc: "专属纪念NFT，仅限我们的早期测试网用户。错过了吗？别担心，还有下一轮空投，资格基于排行榜排名。",
    mintTitle: "铸造 NFT",
    mintSubtitle: "创建您的专属数字藏品",
    mintCount: "铸造次数",
    holders: "持有者",
    eligible: "有资格",
    minted: "已铸造",
    free: "免费",
    minting: "正在铸造…",
    hideScamWicks: "隐藏欺诈蜡烛",
    alreadyMinted: "已铸造",
    notEligible: "不符合资格",
    loading: "加载中...",
  },
  JP: {
    trade: "取引",
    connectWallet: "ウォレット接続",
    swap: "スワップ",
    send: "送信",
    to: "宛先",
    limit: "指値",
    pay: "支払い",
    receive: "受取",
    balance: "残高：",
    settings: "設定",
    max: "最大",
    enterAmount: "金額を入力",
    insufficient: "残高不足 ",
    swapSubtitle: "あらゆるトークンの売買",
    limitSubtitle: "指定価格で取引",
    sendSubtitle: "誰にでもトークンを転送",
    docs: "ドキュメント",
    earn: "獲得",
    referrals: "紹介",
    portfolio: "ポートフォリオ",
    languages: "言語",
    networks: "ネットワーク",
    averagePrice: "平均価格",
    priceImpact: "価格影響",
    isWorth: "の価値",
    When: "時期",
    enterRecipient: "受取人を入力",
    enterWalletAddress: "ウォレットアドレスを入力",
    market: "市場",
    Warning: "警告：高い価格影響！あなたの取引は市場価格を5%以上動かします",
    markets: "市場",
    type: "タイプ",
    size: "サイズ",
    price: "価格",
    amountFilled: "約定量",
    active: "アクティブ",
    time: "時間",
    view: "表示",
    amount: "金額",
    all: "すべて",
    buy: "買い",
    sell: "売り",
    noOpenOrders: "現在アクティブな注文はありません",
    noTradeHistory: "取引履歴なし",
    noOrderHistory: "注文履歴なし",
    cancelAll: "すべてキャンセル",
    openOrders: "未約定注文",
    tradeHistory: "取引履歴",
    orderHistory: "注文履歴",
    no: "いいえ",
    yes: "はい",
    total: "合計",
    Spread: "スプレッド",
    orderbook: "注文板",
    trades: "取引",
    availableLiquidity: "利用可能な流動性",
    dayVolume: "24時間取引量",
    dayHigh: "24時間高値",
    dayLow: "24時間安値",
    dayChange: "24時間変動",
    selectAToken: "トークンを選択",
    selectTokenSubtitle: "デフォルトリストからトークンを選択するか、シンボルまたはアドレスで検索してください。",
    searchToken: "シンボルまたはアドレスで検索",
    slippage: "最大スリッページ",
    partialFill: "部分約定",
    assets: "資産",
    USDvalue: "USD価値",
    noWallet: "ウォレットをお持ちでない？",
    createWallet: " 作成する",
    totalAccountValue: "総口座価値",
    totalVolume: "24時間取引量",
    tradeValue: "取引価値",
    filled: "約定済",
    canceled: "キャンセル済",
    status: "ステータス",
    mid: "仲値",
    placeOrder: "注文する",
    avgPrice: "平均価格",
    connectWalletSubtitle: "ウォレットを接続して取引を開始。",
    success: "成功",
    viewOnExplorer: "エクスプローラーで表示",
    online: "オンライン",
    offline: "オフライン",
    twitter: "Twitter",
    discord: "Discord",
    beta: "ベータ",
    installed: "インストール済",
    popular: "人気",
    chart: "チャート",
    copied: "コピー済",
    copyTokenAddress: "トークンアドレスをコピー",
    clickCopyAddress: "クリックしてアドレスをコピー",
    visitTokenWebsite: "トークンのウェブサイトを訪問",
    copy: "コピー",
    actions: "アクション",
    graphConnectWallet: "ポートフォリオを表示するにはウォレットを接続してください。",
    noTokensDetected: "トークンが検出されません",
    performance: "パフォーマンス",
    balances: "残高",
    welcome: "ようこそ",
    portfolioValue: "ポートフォリオ価値",
    approve: "承認",
    wrap: "ラップ",
    unwrap: "アンラップ",
    useMarket: "市場を使用",
    onlyCurrentMarket: "この市場のみ",
    limitSettings: "指値設定",
    swapSettings: "スワップ設定",
    left: "左",
    right: "右",
    customizableSubtitle: "取引体験をカスタマイズ。",
    tradePanelPosition: "取引パネル位置",
    orderbookPosition: "注文板位置",
    side: "サイド",
    panel: "パネル",
    revertToDefault: "デフォルトに戻す",
    language: "言語",
    referralSettings: "紹介設定",
    changeusedref: "使用中の紹介コードを変更",
    setRef: "紹介を設定",
    createOrViewRefLink: "紹介リンクを作成または表示",
    yourreflink: "あなたの紹介リンク",
    copyLink: "リンクをコピー",
    earnings: "収益",
    totalfees: "合計手数料",
    nothingtoclaim: "請求するものがありません",
    claimfees: "手数料を請求",
    simpleView: "シンプルビュー",
    amountFilledSubtitle: "この注文が約定したトークンの量",
    tradeValueSubtitle: "取引の総価値",
    statusSubtitle: "この注文の約定状況",
    signTransaction: "トランザクションに署名",
    addLiquidityOnly: "流動性のみ追加",
    addLiquidityOnlySubtitle: "有効にすると、この注文がメイカー注文として注文板に追加されることを確認します",
    claimTitle: "収益を請求",
    totalClaim: "合計請求可能",
    shareEarn: "共有して稼ぐ",
    customize: "カスタマイズ",
    create: "作成",
    noLink: "紹介リンクを作成して稼ぎ始めましょう！",
    communityRewards: "コミュニティ報酬",
    communityRewardsText: "25％のコミッションを獲得し、紹介したユーザーに25％の手数料割引を提供",
    instantTracking: "インスタント追跡",
    instantTrackingText: "紹介プログラムからの収益はすぐに請求可能",
    tierBenefits: "インセンティブ乗数",
    tierBenefitsText: "あなたと紹介したユーザーの両方がより多くの報酬を獲得",
    usingCode: "コード使用中：",
    enteracode: "紹介コードを入力",
    earningsDashboard: "収益ダッシュボード",
    earningsSubtitle: "紹介報酬を追跡して請求",
    totalClaimable: "合計請求可能",
    tokenBreakdown: "トークン内訳",
    availableToClaim: "請求可能",
    referralsHelp: "紹介プログラムから獲得した手数料を請求します。手数料は支払われたトークンで収集され、いつでも請求できます。",
    learnMore: "詳細を見る",
    noSelfRefer: "自分の紹介コードは使用できません",
    customizeWarning: "カスタムリンクを変更すると、以前のリンクが機能しなくなります。",
    createWarning: "カスタム紹介リンクを作成",
    referralSubtitle: "友人やクリエイターの紹介コードを使用して25％の手数料割引を受けましょう！",
    yourLink: "あなたの紹介リンク：",
    createCode: "紹介コードを作成",
    signTxn: "トランザクションに署名",
    getHelp: "ヘルプを取得",
    totalVol: "総取引量",
    activeOrders: "アクティブな注文",
    details: "詳細",
    account: "アカウント",
    accountSubtitle: "ウォレットの最近のアクティビティの概要",
    toggle: "数字の表示を切り替え",
    day: "24時間",
    week: "1週間",
    weektwo: "2週間",
    month: "1ヶ月",
    past: "過去",
    portValue: "ポートフォリオ価値",
    slippageHelp: "この取引の予想価格と実行価格の最大許容差異率",
    averagePriceHelp: "この取引の推定平均実行価格",
    priceImpactHelp: "この取引によって引き起こされる市場価格の推定変動",
    nofeeforwrap: "ETHのラップとアンラップは1:1で、手数料はかかりません",
    takerfeeexplanation: "テイカー注文は少額の手数料を支払います",
    makerfeeexplanation: "メイカー注文は手数料がかかりません",
    fee: "手数料",
    cancel: "キャンセル",
    switchto: "切り替え",
    insufficientLiquidity: "流動性不足",
    insufficientLiquidityWarning: "警告：流動性不足。この取引を複数の小さな注文に分けるか、部分約定を有効にしてみてください",
    insufficientLiquidityWarningMultihop: "警告：流動性不足。この取引を複数の小さな注文に分けてみてください",
    priceOutOfRangeBuy: "ポストオンリー価格が高すぎます",
    priceOutOfRangeSell: "ポストオンリー価格が低すぎます",
    clearRef: "紹介コードをクリア",
    comingSoon: "近日公開...",
    earnDesc: "暗号資産で稼ぐ新しい方法を提供するため懸命に取り組んでいます。アップデートをお待ちください！",
    showOB: "注文板を表示",
    showOC: "注文センターを表示",
    priceOutOfRangeWarningBuy: "警告：指値が最低売り価格より高いです。この取引はテイカー注文として実行される可能性があります",
    priceOutOfRangeWarningSell: "警告：指値が最高買い価格より低いです。この取引はテイカー注文として実行される可能性があります",
    limitPrice: "指値価格",
    limitPriceSubtitle: "注文が実行される設定価格",
    partialFillSubtitle: "有効にすると、スリッページが超過した場合に部分実行を許可",
    sHigh: "セッション高値",
    sLow: "セッション安値",
    hideBalances: "残高を隠す",
    disconnect: "接続解除",
    tradingStats: "取引統計",
    refStats: "紹介統計",
    claimableRewards: "請求可能な報酬",
    myCode: "自分のコード：",
    noCode: "コードがありませんか？作成する",
    bal: "残高",
    website: "ウェブサイト",
    terms: "利用規約",
    view_documentation: "Crystalについて学ぶ",
    visit_homepage: "Crystalのウェブサイトを訪問",
    read_terms: "法的条件",
    join_community: "Crystalのコミュニティに参加",
    follow_updates: "Crystalの更新をフォロー",
    more: "もっと見る",
    onlyCurrentMarketHelp: "この市場の注文のみを表示",
    swapComplete: "スワップ完了",
    limitComplete: "指値注文完了",
    sendComplete: "送信完了",
    limitCancelled: "指値注文キャンセル済",
    fillComplete: "注文約定完了",
    wrapComplete: "ラップ完了",
    unwrapComplete: "アンラップ完了",
    approveComplete: "承認完了",
    basic: "ベーシック",
    pro: "プロ",
    searchMarkets: "市場を検索",
    clear: "クリア",
    volume: "取引量",
    byConnecting: "ウォレットを接続することで、Crystalの",
    termsOfService: "利用規約",
    andConsentTo: "に同意し、",
    privacyPolicy: "プライバシーポリシー",
    enterReferralCode: "紹介コードを入力",
    setReferral: "紹介を設定",
    clearReferralLink: "紹介コードをクリア",
    codeTaken: "コードは使用中",
    invalid: "無効",
    requestingConnection: "接続をリクエスト中",
    confirmConnection1: "ブラウザ拡張機能で",
    confirmConnection2: "接続を確認して続行",
    lessThanMinSize: "指値注文サイズは >1 USDC である必要があります",
    enterLimitPrice: "指値価格を入力",
    advancedView: "詳細ビュー",
    basicView: "基本ビュー",
    advancedViewText: "マーケットをマスター",
    basicViewText: "簡単に取引",
    noTokens: "トークンが見つかりません",
    noMarkets: "市場が見つかりません",
    toNavigate: "ナビゲート",
    toSelect: "選択",
    toClose: "閉じる",
    pleaseEnterCode: "紹介コードを入力してください",
    transactionHistory: "取引履歴",
    search: "検索",
    minimumSize: "最小サイズ",
    enableFilter: "フィルターを有効化",
    last: "最後",
    scale: "スケール",
    noTransactionsYet: "取引はまだありません",
    filledAt: "約定価格",
    start: "開始",
    end: "終了",
    skew: "歪み",
    orders: "注文",
    enterStartPrice: "開始価格を入力",
    enterEndPrice: "終了価格を入力",
    startPriceHigh: "開始価格が高すぎます",
    startPriceLow: "開始価格が低すぎます",
    endPriceHigh: "終了価格が高すぎます",
    endPriceLow: "終了価格が低すぎます",
    scaleMinSize: "最小注文サイズは >1 USDC である必要があります",
    enterOrders: "注文数を入力",
    enterSkew: "サイズの歪みを入力",
    transactionDetails: "トランザクション詳細",
    swapDetails: "スワップ詳細",
    limitOrderDetails: "指値注文詳細",
    sendDetails: "送信詳細",
    cancelDetails: "キャンセル詳細",
    fillDetails: "約定詳細",
    wrapDetails: "ラップ詳細",
    unwrapDetails: "アンラップ詳細",
    approveDetails: "承認詳細",
    generalInfo: "トランザクション情報",
    txType: "トランザクションタイプ",
    txTime: "トランザクション時間",
    txHash: "トランザクションハッシュ",
    tokenInfo: "トークン情報",
    fromToken: "入力トークン",
    toToken: "出力トークン",
    recipientInfo: "受取人情報",
    contractInfo: "コントラクト情報",
    address: "アドレス",
    token: "トークン",
    feeInfo: "手数料情報",
    gasUsed: "使用ガス",
    gasPrice: "ガス価格",
    totalFee: "合計手数料",
    back: "戻る",
    at: "時点",
    leaderboard: "リーダーボード",
    orderType: "注文タイプ",
    editAccountTitle: "アカウント編集",
    editAccountSubtitle: "ユーザー名とプロフィール写真を変更",
    username: "ユーザー名",
    chooseNewPhoto: "新しい写真を選択",
    saveChanges: "変更を保存",
    viewRules: "ルールを表示",
    earned: "獲得済",
    rank: "ランク",
    editAccount: "アカウント編集",
    createAccount: "アカウント作成",
    user: "ユーザー",
    totalXP: "合計XP",
    choosePhoto: "写真を選択",
    next: "次へ",
    skip: "スキップ",
    complete: "完了",
    challengeOverview: "クリスタル：シーズン0の紹介",
    learnHowToCompete: "クリスタルを獲得するために競争",
    precisionMatters: "指値注文を出す",
    placeYourBids: "仲値に近い指値注文を出してください。近いほど良いです。",
    earnCrystals: "クリスタルを獲得",
    midsGiveYou: "注文が流動性を提供するとクリスタルを受け取ります。",
    claimRewards: "報酬を受け取る",
    competeOnLeaderboards: "リーダーボードを登り、将来のプロトコル所有権の一部を獲得しましょう。",
    continueAsGuest: "ゲストとして続ける",
    getStarted: "始める",
    of: "の",
    page: "ページ",
    viewYourPosition: "あなたの位置を表示",
    mint: "ミント",
    limitFailed: "指値注文失敗",
    sendFailed: "送信取引失敗",
    sendingTransaction: "トランザクション送信中",
    swapFailed: "スワップ取引失敗",
    swapFailedDetails: "スワップ失敗詳細",
    sendFailedDetails: "送信失敗詳細",
    limitFailedDetails: "指値失敗詳細",
    failed: "失敗",
    errorInfo: "エラー情報",
    attemptedSwap: "試行されたスワップ",
    attemptedSend: "試行された送信",
    sendTo: "送信先",
    done: "完了",
    deposit: "入金",
    depositWarning: "入金はMonadネットワーク上で送信する必要があります。ウォレットはセルフカストディアルであり、Crystalは資金にアクセスできません。",
    audioNotifications: "音声通知を有効化",
    connectYourWallet: "ウォレットを接続",
    connectYourWalletSubtitle: "リーダーボードを表示するにはウォレットを接続してください",
    searchAMarket: "市場を検索",
    browsePairs: "取引ペアを閲覧",
    custom: "カスタム",
    confirmSwap: "スワップを確認",
    highPriceImpactMessage: "警告！高い価格影響！あなたの取引は市場価格を5%以上動かします",
    showTradeMarkers: "取引マーカーを表示",
    usersReferred: "紹介したユーザー",
    editUsername: "ユーザー名を編集",
    bonusCommission: "ボーナスコミッション",
    editUsernameSubtitle: "このユーザー名はリーダーボード上ですべての人に表示されます。",
    yourWalletAddress: "あなたのウォレットアドレス",
    usernameAlreadyTaken: "ユーザー名はすでに使用されています",
    minUsernameLength: "ユーザー名は少なくとも3文字必要です",
    usernameFilter: "ユーザー名には文字、数字、アンダースコアのみを含めることができます",
    maxUsernameLength: "ユーザー名は20文字未満である必要があります",
    showChartOrders: "チャート注文を表示",
    bonusCommision: "ボーナスコミッション",
    edit: "編集",
    shareEarnText: "友達と紹介リンクを共有して、彼らの手数料の25%を獲得しましょう。",
    totalUsersReferred: "総紹介ユーザー数",
    scaleTooltip: "1回のトランザクションで特定の価格範囲内に複数の指値注文を出す",
    setRefFailed: "紹介コードの設定に失敗しました、コードが無効かもしれません",
    favorites: "お気に入り",
    lsts: "LST",
    stablecoins: "ステーブルコイン",
    memes: "ミームコイン",
    pointMultiplier: "ポイント乗数",
    crystalsFromReferrals: "紹介からのクリスタル",
    refAd: "紹介コードで全手数料の最大50%のリベートを獲得",
    monadDesc: "Monadは、1万件以上のTPSに対応した革新的で高性能なEVM互換ブロックチェーンのネイティブトークンです。",
    wMonDesc: "MON（Monadのネイティブトークン）をERC-20規格に対応させたラッパートークンで、スマートコントラクトとの互換性を高めます。",
    wethDesc: "イーサリアムのネイティブトークン（ETH）をERC-20形式に変換したラッパートークンで、スマートコントラクトとの互換性があります。",
    wbtcDesc: "Monadネットワーク上で提供されるビットコインのERC-20ラッパートークンです。",
    wsolDesc: "Solanaのネイティブトークン（SOL）をERC-20形式に変換したラッパートークンで、スマートコントラクトとの互換性を高めます。",
    usdtDesc: "世界で最も広く使われているステーブルコインで、米ドルと1:1で連動しています。",
    smonDesc: "sMONは、KintsuがMonad上で提供するDAO指向の流動性ステーキングトークンで、ステーキング報酬を得ながらエコシステム内での利用が可能です。",
    aprmonDesc: "aPrioriが提供するMEV活用型Monad流動ステーキングトークンです。",
    shmonDesc: "shMON：Monad上で最高水準のステーキング報酬を実現する、世界初のホリスティック流動ステーキングトークンです。",
    dakDesc: "Molandakは伝統と勇気の象徴であり、困難に立ち向かう勇者たちの拠点です。",
    chogDesc: "Chogは知性・戦略・勤勉さを重んじる賢者たちのためのハウスです。",
    yakiDesc: "Moyakiは、謙虚な始まりから成長し、成功への強い意志を持つ人々のために存在します。",
    mintDesc: "最初期のテストネット参加者向けの限定記念NFTです。逃しましたか？心配しないで、次回のドロップも予定されています。リーダーボードの順位に基づいて参加資格が決まります。",
    mintTitle: "NFTをミント",
    mintSubtitle: "あなた専用のデジタルコレクティブルを作成",
    mintCount: "ミント数",
    holders: "ホルダー数",
    eligible: "対象",
    minted: "ミント済み",
    free: "無料",
    minting: "ミント中…",
    hideScamWicks: "詐欺ウィックを非表示",
    alreadyMinted: "すでにミント済み",
    notEligible: "対象外",
    loading: "読み込み中",
  },
  KR: {
    trade: '거래',
    connectWallet: '지갑 연결',
    swap: '스왑',
    send: '보내기',
    to: '수신처',
    limit: '지정가',
    pay: '지불',
    receive: '받기',
    balance: '잔액:',
    settings: '설정',
    max: '최대',
    enterAmount: '금액을 입력하세요',
    insufficient: '잔액 부족 ',
    swapSubtitle: '모든 토큰 구매 및 판매',
    limitSubtitle: '지정된 가격에 거래',
    sendSubtitle: '누구에게나 토큰 전송',
    docs: '문서',
    earn: '수익',
    referrals: '추천인',
    portfolio: '포트폴리오',
    languages: '언어',
    networks: '네트워크',
    averagePrice: '평균 가격',
    priceImpact: '가격 영향',
    isWorth: '가치',
    When: '시기',
    enterRecipient: '수신자를 입력하세요',
    enterWalletAddress: '지갑 주소 입력',
    market: '시장',
    Warning: '경고: 높은 가격 영향! 거래가 시장 가격을 5% 이상 변동시킵니다',
    markets: '시장',
    type: '유형',
    size: '규모',
    price: '가격',
    amountFilled: '체결된 금액',
    active: '활성',
    time: '시간',
    view: '보기',
    amount: '금액',
    all: '전체',
    buy: '구매',
    sell: '판매',
    noOpenOrders: '현재 활성화된 주문 없음',
    noTradeHistory: '거래 내역 없음',
    noOrderHistory: '주문 내역 없음',
    cancelAll: '전체 취소',
    openOrders: '미체결 주문',
    tradeHistory: '거래 내역',
    orderHistory: '주문 내역',
    no: '아니오',
    yes: '예',
    total: '총',
    Spread: '스프레드',
    orderbook: '호가창',
    trades: '거래',
    availableLiquidity: '사용 가능한 유동성',
    dayVolume: '24시간 거래량',
    dayHigh: '24시간 최고가',
    dayLow: '24시간 최저가',
    dayChange: '24시간 변동',
    selectAToken: '토큰 선택',
    selectTokenSubtitle: '기본 목록에서 토큰을 선택하거나 심볼 또는 주소로 검색하세요.',
    searchToken: '심볼 또는 주소로 검색',
    slippage: '최대 슬리피지',
    partialFill: '부분 체결',
    assets: '자산',
    USDvalue: 'USD 가치',
    noWallet: '지갑이 없으신가요?',
    createWallet: ' 생성하기',
    totalAccountValue: '총 계정 가치',
    totalVolume: '24시간 거래량',
    tradeValue: '거래 가치',
    filled: '체결됨',
    canceled: '취소됨',
    status: '상태',
    mid: '중간가',
    placeOrder: '주문 하기',
    avgPrice: '평균 가격',
    connectWalletSubtitle: '거래를 시작하려면 지갑을 연결하세요.',
    success: '성공',
    viewOnExplorer: '익스플로러에서 보기',
    online: '온라인',
    offline: '오프라인',
    twitter: '트위터',
    discord: '디스코드',
    beta: '베타',
    installed: '설치됨',
    popular: '인기',
    chart: '차트',
    copied: '복사됨',
    copyTokenAddress: '토큰 주소 복사',
    clickCopyAddress: '클릭하여 주소 복사',
    visitTokenWebsite: '토큰 웹사이트 방문',
    copy: '복사',
    actions: '작업',
    graphConnectWallet: '포트폴리오를 보려면 지갑을 연결하세요.',
    noTokensDetected: '토큰이 감지되지 않음',
    performance: '성과',
    balances: '잔액',
    welcome: '환영합니다',
    portfolioValue: '포트폴리오 가치',
    approve: '승인',
    wrap: '랩',
    unwrap: '언랩',
    useMarket: '시장가 사용',
    onlyCurrentMarket: '현재 시장만',
    limitSettings: '지정가 설정',
    swapSettings: '스왑 설정',
    left: '왼쪽',
    right: '오른쪽',
    customizableSubtitle: '거래 경험을 맞춤 설정하세요.',
    tradePanelPosition: '거래 패널 위치',
    orderbookPosition: '호가창 위치',
    side: '방향',
    panel: '패널',
    revertToDefault: '기본값으로 복원',
    language: '언어',
    referralSettings: '추천인 설정',
    changeusedref: '사용 중인 추천인 변경',
    setRef: '추천인 설정',
    createOrViewRefLink: '추천 링크 생성 또는 보기',
    yourreflink: '내 추천 링크',
    copyLink: '링크 복사',
    earnings: '수익',
    totalfees: '총 수수료',
    nothingtoclaim: '청구할 항목 없음',
    claimfees: '수수료 청구',
    simpleView: '간단 보기',
    amountFilledSubtitle: '이 주문에 대해 체결된 토큰 양',
    tradeValueSubtitle: '거래의 총 가치',
    statusSubtitle: '이 주문의 체결 상태',
    signTransaction: '거래 서명',
    addLiquidityOnly: '유동성만 추가',
    addLiquidityOnlySubtitle: '활성화되면 이 주문이 메이커 주문으로 호가창에 추가되도록 합니다',
    claimTitle: '수익 청구하기',
    totalClaim: '총 청구 가능',
    shareEarn: '공유하고 수익 얻기',
    customize: '커스터마이즈',
    create: '생성',
    noLink: '수익을 얻기 위해 추천 링크를 생성하세요!',
    communityRewards: '커뮤니티 보상',
    communityRewardsText: '25% 수수료를 받고 추천한 사용자에게 25% 수수료 할인 제공',
    instantTracking: '즉시 추적',
    instantTrackingText: '추천 프로그램에서 얻은 수익은 즉시 청구 가능합니다',
    tierBenefits: '인센티브 배율',
    tierBenefitsText: '사용자와 추천받은 사용자 모두 더 많은 보상을 받게 됩니다',
    usingCode: '사용 중인 코드:',
    enteracode: '추천 코드 입력',
    earningsDashboard: '수익 대시보드',
    earningsSubtitle: '추천 보상 추적 및 청구',
    totalClaimable: '총 청구 가능',
    tokenBreakdown: '토큰 내역',
    availableToClaim: '청구 가능',
    referralsHelp: '추천 프로그램에서 얻은 수수료를 청구하세요. 수수료는 지불된 토큰으로 수집되며 언제든지 청구할 수 있습니다.',
    learnMore: '더 알아보기',
    noSelfRefer: '자신의 추천 코드는 사용할 수 없습니다',
    customizeWarning: '맞춤 링크를 변경하면 이전 링크는 작동이 중지됩니다.',
    createWarning: '맞춤 추천 링크 생성',
    referralSubtitle: '친구나 크리에이터의 추천 코드를 사용하면 25% 수수료 할인을 받을 수 있습니다!',
    yourLink: '내 추천 링크:',
    createCode: '추천 코드 생성',
    signTxn: '거래 서명',
    getHelp: '도움 받기',
    totalVol: '총 거래량',
    activeOrders: '활성 주문',
    details: '세부 정보',
    account: '계정',
    accountSubtitle: '지갑의 최근 활동 개요',
    toggle: '숫자 표시 전환',
    day: '24시간',
    week: '1주',
    weektwo: '2주',
    month: '1개월',
    past: '지난',
    portValue: '포트폴리오 가치',
    slippageHelp: '이 거래의 예상 가격과 실행 가격 사이의 최대 백분율 차이',
    averagePriceHelp: '이 거래에 대한 예상 평균 실행 가격',
    priceImpactHelp: '이 거래로 인한 시장 가격의 예상 변화',
    nofeeforwrap: 'ETH 랩핑 및 언랩핑은 1:1이며 수수료가 발생하지 않습니다',
    takerfeeexplanation: '테이커 주문은 소액의 수수료가 부과됩니다',
    makerfeeexplanation: '메이커 주문에는 수수료가 부과되지 않습니다',
    fee: '수수료',
    cancel: '취소',
    switchto: '전환',
    insufficientLiquidity: '유동성 부족',
    insufficientLiquidityWarning: '경고: 유동성 부족. 이 거래를 여러 개의 작은 주문으로 나누거나 부분 체결을 활성화하세요',
    insufficientLiquidityWarningMultihop: '경고: 유동성 부족. 이 거래를 여러 개의 작은 주문으로 나누세요',
    priceOutOfRangeBuy: '포스트 온리 가격이 너무 높음',
    priceOutOfRangeSell: '포스트 온리 가격이 너무 낮음',
    clearRef: '추천 코드 지우기',
    comingSoon: '준비 중...',
    earnDesc: '암호화폐로 수익을 얻을 수 있는 새로운 방법을 열심히 준비 중입니다. 업데이트를 기대해 주세요!',
    showOB: '호가창 표시',
    showOC: '주문 센터 표시',
    priceOutOfRangeWarningBuy: '경고: 지정가가 최저 매도가보다 높습니다. 이 거래는 테이커 주문으로 실행될 가능성이 높습니다',
    priceOutOfRangeWarningSell: '경고: 지정가가 최고 매수가보다 낮습니다. 이 거래는 테이커 주문으로 실행될 가능성이 높습니다',
    limitPrice: '지정가',
    limitPriceSubtitle: '주문이 실행되도록 설정된 가격',
    partialFillSubtitle: '활성화되면 슬리피지가 초과될 경우 부분 실행 허용',
    sHigh: '세션 최고가',
    sLow: '세션 최저가',
    hideBalances: '잔액 숨기기',
    disconnect: '연결 해제',
    tradingStats: '거래 통계',
    refStats: '추천인 통계',
    claimableRewards: '청구 가능한 보상',
    myCode: '내 코드:',
    noCode: '코드가 없으신가요? 생성하기',
    bal: '잔액',
    website: '웹사이트',
    terms: '이용 약관',
    view_documentation: 'Crystal에 대해 알아보기',
    visit_homepage: 'Crystal 웹사이트 방문',
    read_terms: '법적 이용 약관',
    join_community: 'Crystal 커뮤니티 참여',
    follow_updates: 'Crystal 업데이트 팔로우',
    more: '더 보기',
    onlyCurrentMarketHelp: '이 시장의 주문만 표시',
    swapComplete: '스왑 완료',
    limitComplete: '지정가 주문 완료',
    sendComplete: '전송 완료',
    limitCancelled: '지정가 주문 취소됨',
    fillComplete: '주문 체결됨',
    wrapComplete: '랩 완료',
    unwrapComplete: '언랩 완료',
    approveComplete: '승인 완료',
    basic: '기본',
    pro: '프로',
    searchMarkets: '시장 검색',
    clear: '지우기',
    volume: '거래량',
    byConnecting: '지갑을 연결함으로써 Crystal의',
    termsOfService: '서비스 이용 약관',
    andConsentTo: '에 동의하고',
    privacyPolicy: '개인정보 보호정책',
    enterReferralCode: '추천 코드 입력',
    setReferral: '추천인 설정',
    clearReferralLink: '추천 코드 지우기',
    codeTaken: '사용 중인 코드',
    invalid: '유효하지 않음',
    requestingConnection: '연결 요청 중',
    confirmConnection1: '계속하려면',
    confirmConnection2: '브라우저 확장 프로그램에서 연결을 확인하세요',
    lessThanMinSize: '지정가 주문 크기는 1 USDC보다 커야 합니다',
    enterLimitPrice: '지정가 입력',
    advancedView: '고급 보기',
    basicView: '기본 보기',
    advancedViewText: '시장 마스터하기',
    basicViewText: '쉽게 거래하기',
    noTokens: '토큰을 찾을 수 없음',
    noMarkets: '시장을 찾을 수 없음',
    toNavigate: '탐색',
    toSelect: '선택',
    toClose: '닫기',
    pleaseEnterCode: '추천 코드를 입력하세요',
    transactionHistory: '거래 내역',
    search: '검색',
    minimumSize: '최소 크기',
    enableFilter: '필터 활성화',
    last: '마지막',
    scale: '스케일',
    noTransactionsYet: '아직 거래 내역 없음',
    filledAt: '체결됨',
    start: '시작',
    end: '종료',
    skew: '왜곡',
    orders: '주문',
    enterStartPrice: '시작 가격 입력',
    enterEndPrice: '종료 가격 입력',
    startPriceHigh: '시작 가격이 너무 높음',
    startPriceLow: '시작 가격이 너무 낮음',
    endPriceHigh: '종료 가격이 너무 높음',
    endPriceLow: '종료 가격이 너무 낮음',
    scaleMinSize: '가장 작은 주문 크기는 1 USDC보다 커야 합니다',
    enterOrders: '주문 수 입력',
    enterSkew: '크기 왜곡 입력',
    transactionDetails: '거래 세부 정보',
    swapDetails: '스왑 세부 정보',
    limitOrderDetails: '지정가 주문 세부 정보',
    sendDetails: '전송 세부 정보',
    cancelDetails: '취소 세부 정보',
    fillDetails: '체결 세부 정보',
    wrapDetails: '랩 세부 정보',
    unwrapDetails: '언랩 세부 정보',
    approveDetails: '승인 세부 정보',
    generalInfo: '거래 정보',
    txType: '거래 유형',
    txTime: '거래 시간',
    txHash: '거래 해시',
    tokenInfo: '토큰 정보',
    fromToken: '입력 토큰',
    toToken: '출력 토큰',
    recipientInfo: '수신자 정보',
    contractInfo: '계약 정보',
    address: '주소',
    token: '토큰',
    feeInfo: '수수료 정보',
    gasUsed: '사용된 가스',
    gasPrice: '가스 가격',
    totalFee: '총 수수료',
    back: '뒤로',
    at: '에',
    leaderboard: '리더보드',
    orderType: '주문 유형',
    editAccountTitle: "계정 편집",
    editAccountSubtitle: "사용자 이름 및 프로필 사진 변경",
    username: "사용자 이름",
    chooseNewPhoto: "새 사진 선택",
    saveChanges: "변경 사항 저장",
    viewRules: "규칙 보기",
    earned: "획득함",
    rank: "랭크",
    editAccount: "계정 편집",
    createAccount: "계정 생성",
    user: "사용자",
    totalXP: "총 XP",
    choosePhoto: "사진 선택",
    next: "다음",
    skip: "건너뛰기",
    complete: "완료",
    challengeOverview: "Crystal 소개: 시즌 0",
    learnHowToCompete: "Crystal을 얻기 위해 경쟁하세요",
    precisionMatters: "지정가 주문 하기",
    placeYourBids: "중간가 근처에 지정가 주문을 하세요. 가까울수록 좋습니다.",
    earnCrystals: "Crystal 획득",
    midsGiveYou: "주문이 유동성을 제공하면 Crystal을 받습니다.",
    claimRewards: "보상 받기",
    competeOnLeaderboards: "리더보드에서 경쟁하고 미래 프로토콜 소유권의 일부를 획득하세요.",
    continueAsGuest: "게스트로 계속하기",
    getStarted: "시작하기",
    of: "중",
    page: "페이지",
    viewYourPosition: "내 위치 보기",
    mint: "민트",
    limitFailed: '지정가 주문 실패',
    sendFailed: '전송 거래 실패',
    sendingTransaction: '거래 전송 중',
    swapFailed: '스왑 거래 실패',
    swapFailedDetails: '스왑 실패 세부 정보',
    sendFailedDetails: '전송 실패 세부 정보',
    limitFailedDetails: '지정가 실패 세부 정보',
    failed: '실패',
    errorInfo: '오류 정보',
    attemptedSwap: '시도된 스왑',
    attemptedSend: '시도된 전송',
    sendTo: '전송 대상',
    done: '완료',
    deposit: '입금',
    depositWarning: "입금은 Monad 네트워크에서 보내야 합니다. 지갑은 자체 보관형이며, Crystal은 귀하의 자금에 접근할 수 없습니다.",
    audioNotifications: "오디오 알림 활성화",
    connectYourWallet: "지갑 연결하기",
    connectYourWalletSubtitle: "리더보드를 보려면 지갑을 연결하세요",
    searchAMarket: "시장 검색",
    browsePairs: "거래 페어 살펴보기",
    custom: "커스텀",
    confirmSwap: "스왑 확인",
    highPriceImpactMessage: "경고! 높은 가격 영향! 귀하의 거래는 시장 가격을 5% 이상 변동시킵니다",
    showTradeMarkers: "거래 마커 표시",
    usersReferred: "추천된 사용자",
    editUsername: "사용자 이름 편집",
    bonusCommission: "보너스 수수료",
    editUsernameSubtitle: "이 사용자 이름은 리더보드에서 모든 사람에게 표시됩니다.",
    yourWalletAddress: "내 지갑 주소",
    usernameAlreadyTaken: "이미 사용 중인 사용자 이름",
    minUsernameLength: "사용자 이름은 최소 3자 이상이어야 합니다",
    usernameFilter: "사용자 이름은 문자, 숫자, 밑줄만 포함할 수 있습니다",
    maxUsernameLength: "사용자 이름은 20자 미만이어야 합니다",
    showChartOrders: "차트 주문 표시",
    bonusCommision: "보너스 수수료",
    edit: "편집",
    shareEarnText: "친구와 추천 링크를 공유하고 수수료의 25%를 획득하세요.",
    totalUsersReferred: "총 추천 사용자",
    scaleTooltip: "단일 거래로 지정된 가격 범위 내에 여러 지정가 주문 배치",
    setRefFailed: "추천 코드 설정 실패, 코드가 유효하지 않을 수 있습니다",
    favorites: "즐겨찾기",
    lsts: "LST",
    stablecoins: "스테이블코인",
    memes: "밈",
    pointMultiplier: "포인트 배율",
    crystalsFromReferrals: "추천으로 얻은 Crystal",
    refAd: "추천 코드로 모든 수수료에 대해 최대 50% 리베이트 획득",
    monadDesc: "초당 10,000 TPS 이상을 지원하는 혁신적인 고성능 EVM 네트워크인 Monad 블록체인의 기본 토큰입니다.",
    wMonDesc: "스마트 계약과의 더 나은 호환성을 위한 Monad의 네이티브 토큰(MON)의 ERC-20 래퍼입니다.",
    wethDesc: "스마트 계약과의 더 나은 호환성을 위한 이더리움의 네이티브 토큰(ETH)의 ERC-20 래퍼입니다.",
    wbtcDesc: "Monad 네트워크에서의 비트코인의 ERC-20 래퍼입니다.",
    wsolDesc: "스마트 계약과의 더 나은 호환성을 위한 솔라나의 네이티브 토큰(SOL)의 ERC-20 래퍼입니다.",
    usdtDesc: "세계에서 가장 널리 사용되는 스테이블코인으로, 미국 달러에 1:1로 페그되어 있습니다.",
    smonDesc: "sMON은 Kintsu의 Monad 유동적 스테이킹 토큰으로, DAO와 연계되어 있으며, 사용자가 생태계 전반에서 복합성을 유지하면서 스테이킹 보상을 얻을 수 있도록 설계되었습니다.",
    aprmonDesc: "aPriori의 MEV 기반 Monad 유동적 스테이킹",
    shmonDesc: "shMON: 세계 최초의 종합적인 유동적 스테이킹 토큰으로 Monad에서 최고의 스테이킹 보상을 제공합니다.",
    dakDesc: "용기와 전통으로 알려진 Molandak은 도전을 정면으로 마주하는 용감한 이들의 본거지입니다.",
    chogDesc: "Chog는 지성, 전략, 지칠 줄 모르는 직업 윤리를 중시하는 현명하고 근면한 이들을 위한 집입니다.",
    yakiDesc: "Moyaki는 성공하고자 하는 불굴의 의지를 가진 미천한 출신의 사람들을 위해 헤엄칩니다.",
    mintDesc: "초기 테스트넷 사용자만을 위한 독점 기념 NFT입니다. 놓치셨나요? 걱정 마세요. 다음 드롭이 곧 진행되며, 리더보드 순위에 따라 참여 자격이 결정됩니다.",
    mintTitle: "NFT 민팅",
    mintSubtitle: "나만의 디지털 컬렉터블 생성",
    mintCount: "민팅 수",
    holders: "보유자",
    eligible: "자격 있음",
    minted: "민팅 완료",
    free: "무료",
    minting: "민팅 중…",
    hideScamWicks: "사기 꼬리 숨기기",
    alreadyMinted: "이미 민팅됨",
    notEligible: "자격 없음",
    loading: "로딩 중...",
  },
  ES: {
    trade: 'Comerciar',
    connectWallet: 'Conectar Monedero',
    swap: 'Intercambiar',
    send: 'Enviar',
    to: 'A',
    limit: 'Límite',
    pay: 'Pagar',
    receive: 'Recibir',
    balance: 'Saldo:',
    settings: 'Configuración',
    max: 'Máx',
    enterAmount: 'Ingrese un monto',
    insufficient: 'Insuficiente ',
    swapSubtitle: 'Compra y vende cualquier token',
    limitSubtitle: 'Comercia a un precio específico',
    sendSubtitle: 'Transfiere tokens a cualquier persona',
    docs: 'Documentación',
    earn: 'Ganar',
    referrals: 'Referencias',
    portfolio: 'Portafolio',
    languages: 'Idiomas',
    networks: 'Redes',
    averagePrice: 'Precio Promedio',
    priceImpact: 'Impacto en el Precio',
    isWorth: 'vale',
    When: 'Cuando',
    enterRecipient: 'Ingrese un destinatario',
    enterWalletAddress: 'Ingrese dirección de monedero',
    market: 'Mercado',
    Warning: '¡Advertencia: Alto impacto en el precio! Tu operación moverá el precio del mercado más del 5%',
    markets: 'Mercado',
    type: 'Tipo',
    size: 'Tamaño',
    price: 'Precio',
    amountFilled: 'Cantidad Completada',
    active: 'Activo',
    time: 'Tiempo',
    view: 'Ver',
    amount: 'Cantidad',
    all: 'Todo',
    buy: 'Comprar',
    sell: 'Vender',
    noOpenOrders: 'No hay órdenes activas actualmente',
    noTradeHistory: 'No hay historial de operaciones',
    noOrderHistory: 'No hay historial de órdenes',
    cancelAll: 'Cancelar Todo',
    openOrders: 'Órdenes Abiertas',
    tradeHistory: 'Historial de Operaciones',
    orderHistory: 'Historial de Órdenes',
    no: 'No',
    yes: 'Sí',
    total: 'Total',
    Spread: 'Diferencial',
    orderbook: 'Libro de Órdenes',
    trades: 'Operaciones',
    availableLiquidity: 'Liquidez Disponible',
    dayVolume: 'Volumen 24h',
    dayHigh: 'Máximo 24h',
    dayLow: 'Mínimo 24h',
    dayChange: 'Cambio 24h',
    selectAToken: 'Seleccionar un Token',
    selectTokenSubtitle: 'Seleccione un token de nuestra lista predeterminada o búsquelo por su símbolo o dirección.',
    searchToken: 'Buscar por símbolo o dirección',
    slippage: 'Deslizamiento Máximo',
    partialFill: 'Ejecución Parcial',
    assets: 'Activos',
    USDvalue: 'Valor en USD',
    noWallet: '¿No tienes un monedero?',
    createWallet: ' Crear Uno',
    totalAccountValue: 'Valor Total de la Cuenta',
    totalVolume: 'Volumen 24h',
    tradeValue: 'Valor de la Operación',
    filled: 'Completado',
    canceled: 'Cancelado',
    status: 'Estado',
    mid: 'Medio',
    placeOrder: 'Colocar Orden',
    avgPrice: 'Precio Prom.',
    connectWalletSubtitle: 'Conecta tu monedero para comenzar a operar.',
    success: 'Éxito',
    viewOnExplorer: 'Ver en Explorador',
    online: 'EN LÍNEA',
    offline: 'FUERA DE LÍNEA',
    twitter: 'Twitter',
    discord: 'Discord',
    beta: 'Beta',
    installed: 'Instalado',
    popular: 'Popular',
    chart: 'Gráfico',
    copied: 'Copiado',
    copyTokenAddress: 'Copiar dirección del token',
    clickCopyAddress: 'Clic para copiar dirección',
    visitTokenWebsite: 'Visitar sitio web del token',
    copy: 'Copiar',
    actions: 'Acciones',
    graphConnectWallet: 'Conecta tu monedero para ver tu portafolio.',
    noTokensDetected: 'No se detectaron tokens',
    performance: 'RENDIMIENTO',
    balances: 'Saldos',
    welcome: 'Bienvenido',
    portfolioValue: 'Valor del Portafolio',
    approve: 'Aprobar',
    wrap: 'Envolver',
    unwrap: 'Desenvolver',
    useMarket: 'Usar Mercado',
    onlyCurrentMarket: 'Solo este mercado',
    limitSettings: 'Configuración de Límite',
    swapSettings: 'Configuración de Intercambio',
    left: 'Izquierda',
    right: 'Derecha',
    customizableSubtitle: 'Personaliza tu experiencia de trading.',
    tradePanelPosition: 'Posición del Panel de Trading',
    orderbookPosition: 'Posición del Libro de Órdenes',
    side: 'Lado',
    panel: 'Panel',
    revertToDefault: 'Volver a Predeterminado',
    language: 'Idioma',
    referralSettings: 'Configuración de Referencias',
    changeusedref: 'Cambiar Referencia Utilizada',
    setRef: 'Establecer Referencia',
    createOrViewRefLink: 'Crear o Ver Enlace de Referencia',
    yourreflink: 'Tu Enlace de Referencia',
    copyLink: 'Copiar Enlace',
    earnings: 'Ganancias',
    totalfees: 'Comisiones Totales',
    nothingtoclaim: 'Nada que Reclamar',
    claimfees: 'Reclamar Comisiones',
    simpleView: 'Vista Simple',
    amountFilledSubtitle: 'La cantidad de tokens que se han completado para esta orden',
    tradeValueSubtitle: 'El valor total de tu operación',
    statusSubtitle: 'El estado de ejecución de esta orden',
    signTransaction: 'Firmar Transacción',
    addLiquidityOnly: 'Solo Añadir Liquidez',
    addLiquidityOnlySubtitle: 'Si está habilitado, asegura que esta orden se añada al libro como una orden de creador',
    claimTitle: 'Reclama Tus Ganancias',
    totalClaim: 'Total Reclamable',
    shareEarn: 'Compartir y Ganar',
    customize: 'Personalizar',
    create: 'Crear',
    noLink: '¡Crea un enlace de referencia para comenzar a ganar!',
    communityRewards: 'Recompensas Comunitarias',
    communityRewardsText: 'Gana una comisión del 25% y ofrece a tus usuarios referidos un 25% de descuento en comisiones',
    instantTracking: 'Seguimiento Instantáneo',
    instantTrackingText: 'Las ganancias del programa de referidos están disponibles para reclamar al instante',
    tierBenefits: 'Multiplicadores de Incentivos',
    tierBenefitsText: 'Tanto tú como tus usuarios referidos ganarán más recompensas',
    usingCode: 'Usando Código:',
    enteracode: 'Ingresa código de referencia',
    earningsDashboard: 'Panel de Ganancias',
    earningsSubtitle: 'Rastrea y reclama tus recompensas por referidos',
    totalClaimable: 'Total Reclamable',
    tokenBreakdown: 'Desglose de Tokens',
    availableToClaim: 'Disponible para reclamar',
    referralsHelp: 'Reclama tus comisiones ganadas del programa de referidos. Las comisiones se cobran en el token en que fueron pagadas y pueden reclamarse en cualquier momento.',
    learnMore: 'Saber Más',
    noSelfRefer: 'No puedes usar tu propio código de referencia',
    customizeWarning: 'Si cambias tu enlace personalizado, el anterior dejará de funcionar.',
    createWarning: 'Crear un enlace de referencia personalizado',
    referralSubtitle: '¡Obtén un 25% de descuento en comisiones cuando uses el código de referencia de un amigo o creador!',
    yourLink: 'Tu enlace de referencia:',
    createCode: 'Crear código de referencia',
    signTxn: 'Firmar Transacción',
    getHelp: 'Obtener Ayuda',
    totalVol: 'Volumen Total',
    activeOrders: 'Órdenes Activas',
    details: 'Detalles',
    account: 'CUENTA',
    accountSubtitle: 'Resumen de la actividad reciente de tu monedero',
    toggle: 'Alternar visibilidad de números',
    day: '24h',
    week: '1s',
    weektwo: '2s',
    month: '1m',
    past: 'pasado',
    portValue: 'Valor del Portafolio',
    slippageHelp: 'La diferencia porcentual máxima entre el precio esperado y el precio ejecutado de esta operación',
    averagePriceHelp: 'El precio promedio estimado de ejecución para esta operación',
    priceImpactHelp: 'El cambio estimado en el precio del mercado causado por esta operación',
    nofeeforwrap: 'Envolver y desenvolver ETH es 1:1 y no incurre en ninguna comisión',
    takerfeeexplanation: 'Las órdenes tomadoras pagan una pequeña comisión',
    makerfeeexplanation: 'A las órdenes creadoras no se les cobra ninguna comisión',
    fee: 'Comisión',
    cancel: 'Cancelar',
    switchto: 'Cambiar a',
    insufficientLiquidity: 'Liquidez Insuficiente',
    insufficientLiquidityWarning: 'Advertencia: Liquidez insuficiente. Intenta dividir esta operación en múltiples órdenes más pequeñas o habilitar la ejecución parcial',
    insufficientLiquidityWarningMultihop: 'Advertencia: Liquidez insuficiente. Intenta dividir esta operación en múltiples órdenes más pequeñas',
    priceOutOfRangeBuy: 'Precio solo post demasiado alto',
    priceOutOfRangeSell: 'Precio solo post demasiado bajo',
    clearRef: 'Borrar Código de Referencia',
    comingSoon: 'Próximamente...',
    earnDesc: '¡Estamos trabajando arduamente para traerte nuevas formas de ganar con tu cripto. Mantente atento para actualizaciones!',
    showOB: 'Mostrar Libro de Órdenes',
    showOC: 'Mostrar Centro de Órdenes',
    priceOutOfRangeWarningBuy: 'Advertencia: Precio límite más alto que el precio de venta más bajo. Esta operación probablemente se ejecutará como una orden tomadora',
    priceOutOfRangeWarningSell: 'Advertencia: Precio límite más bajo que el precio de compra más alto. Esta operación probablemente se ejecutará como una orden tomadora',
    limitPrice: 'Precio Límite',
    limitPriceSubtitle: 'El precio al que está configurada tu orden para ejecutarse',
    partialFillSubtitle: 'Si está habilitado, permite la ejecución parcial si se excede el deslizamiento',
    sHigh: 'Máximo de Sesión',
    sLow: 'Mínimo de Sesión',
    hideBalances: 'Ocultar Saldos',
    disconnect: 'Desconectar',
    tradingStats: 'ESTADÍSTICAS DE TRADING',
    refStats: 'ESTADÍSTICAS DE REFERIDOS',
    claimableRewards: 'Recompensas Reclamables',
    myCode: 'Mi Código:',
    noCode: '¿No tienes un código? Crea uno',
    bal: 'Saldo',
    website: 'Sitio Web',
    terms: 'Términos de Uso',
    view_documentation: 'Aprende sobre Crystal',
    visit_homepage: 'Visita el sitio web de Crystal',
    read_terms: 'Términos y condiciones legales',
    join_community: 'Únete a la comunidad de Crystal',
    follow_updates: 'Sigue las actualizaciones de Crystal',
    more: 'Más',
    onlyCurrentMarketHelp: 'Solo mostrar órdenes para este mercado',
    swapComplete: 'Intercambio Completado',
    limitComplete: 'Orden Límite Completada',
    sendComplete: 'Envío Completado',
    limitCancelled: 'Orden Límite Cancelada',
    fillComplete: 'Orden Completada',
    wrapComplete: 'Envoltura Completada',
    unwrapComplete: 'Desenvoltura Completada',
    approveComplete: 'Aprobación Completada',
    basic: 'BÁSICO',
    pro: 'Pro',
    searchMarkets: 'Buscar Mercados',
    clear: 'Limpiar',
    volume: 'Volumen',
    byConnecting: 'Al conectar un monedero, aceptas los',
    termsOfService: 'Términos de Servicio',
    andConsentTo: 'de Crystal y consientes su',
    privacyPolicy: 'Política de Privacidad',
    enterReferralCode: 'Ingresar Código de Referencia',
    setReferral: 'Establecer Referencia',
    clearReferralLink: 'Borrar Código de Referencia',
    codeTaken: 'Código ocupado',
    invalid: 'Inválido',
    requestingConnection: 'Solicitando Conexión',
    confirmConnection1: 'Confirma la conexión en la',
    confirmConnection2: 'extensión del navegador para continuar',
    lessThanMinSize: 'El tamaño de la orden límite debe ser >1 USDC',
    enterLimitPrice: 'Ingresa un precio límite',
    advancedView: 'Vista Avanzada',
    basicView: 'Vista Básica',
    advancedViewText: 'Domina los mercados',
    basicViewText: 'Opera con facilidad',
    noTokens: 'No se encontraron tokens',
    noMarkets: 'No se encontraron mercados',
    toNavigate: 'para navegar',
    toSelect: 'para seleccionar',
    toClose: 'para cerrar',
    pleaseEnterCode: 'Por favor ingresa un código de referencia',
    transactionHistory: 'Historial de Transacciones',
    search: 'Buscar',
    minimumSize: 'Tamaño Mínimo',
    enableFilter: 'Habilitar Filtro',
    last: 'Último',
    scale: 'Escala',
    noTransactionsYet: 'Aún no hay transacciones',
    filledAt: 'completado a',
    start: 'Inicio',
    end: 'Fin',
    skew: 'Sesgo',
    orders: 'Órdenes',
    enterStartPrice: 'Ingresa un precio de inicio',
    enterEndPrice: 'Ingresa un precio final',
    startPriceHigh: 'Precio inicial demasiado alto',
    startPriceLow: 'Precio inicial demasiado bajo',
    endPriceHigh: 'Precio final demasiado alto',
    endPriceLow: 'Precio final demasiado bajo',
    scaleMinSize: 'El tamaño de orden más pequeño debe ser >1 USDC',
    enterOrders: 'Ingresa cantidad de órdenes',
    enterSkew: 'Ingresa sesgo de tamaño',
    transactionDetails: 'Detalles de la Transacción',
    swapDetails: 'Detalles del Intercambio',
    limitOrderDetails: 'Detalles de la Orden Límite',
    sendDetails: 'Detalles del Envío',
    cancelDetails: 'Detalles de la Cancelación',
    fillDetails: 'Detalles de la Ejecución',
    wrapDetails: 'Detalles de la Envoltura',
    unwrapDetails: 'Detalles de la Desenvoltura',
    approveDetails: 'Detalles de la Aprobación',
    generalInfo: 'Información de la Transacción',
    txType: 'Tipo de Tx',
    txTime: 'Hora de Tx',
    txHash: 'Hash de Tx',
    tokenInfo: 'Información del Token',
    fromToken: 'Token de Entrada',
    toToken: 'Token de Salida',
    recipientInfo: 'Información del Destinatario',
    contractInfo: 'Información del Contrato',
    address: 'Dirección',
    token: 'Token',
    feeInfo: 'Información de Comisiones',
    gasUsed: 'Gas Utilizado',
    gasPrice: 'Precio del Gas',
    totalFee: 'Comisión Total',
    back: 'Volver',
    at: 'a',
    leaderboard: 'Tabla de Clasificación',
    orderType: 'Tipo de Orden',
    editAccountTitle: "Editar Cuenta",
    editAccountSubtitle: "Cambia tu nombre de usuario y foto de perfil",
    username: "Nombre de Usuario",
    chooseNewPhoto: "Elegir Nueva Foto",
    saveChanges: "Guardar Cambios",
    viewRules: "Ver Reglas",
    earned: "Ganado",
    rank: "Rango",
    editAccount: "Editar Cuenta",
    createAccount: "Crear Cuenta",
    user: "Usuario",
    totalXP: "XP Total",
    choosePhoto: "Elegir Foto",
    next: "Siguiente",
    skip: "Omitir",
    complete: "Completar",
    challengeOverview: "Presentando Crystals: Temporada 0",
    learnHowToCompete: "Compite para ganar Crystals",
    precisionMatters: "Coloca Órdenes Límite",
    placeYourBids: "Coloca tus órdenes límite cerca del precio medio. Cuanto más cerca, mejor.",
    earnCrystals: "Gana Crystals",
    midsGiveYou: "Recibe Crystals mientras tu orden proporciona liquidez.",
    claimRewards: "Recibe Recompensas",
    competeOnLeaderboards: "Escala en la tabla de clasificación y gánate una parte de la futura propiedad del protocolo.",
    continueAsGuest: "Continuar como Invitado",
    getStarted: "Comenzar",
    of: "de",
    page: "Página",
    viewYourPosition: "Ver Tu Posición",
    mint: "Acuñar",
    limitFailed: 'Orden Límite Fallida',
    sendFailed: 'Envío Fallido',
    sendingTransaction: 'Enviando Transacción',
    swapFailed: 'Intercambio Fallido',
    swapFailedDetails: 'Detalles del Fallo de Intercambio',
    sendFailedDetails: 'Detalles del Fallo de Envío',
    limitFailedDetails: 'Detalles del Fallo de Límite',
    failed: 'Fallido',
    errorInfo: 'Información de Error',
    attemptedSwap: 'Intercambio Intentado',
    attemptedSend: 'Envío Intentado',
    sendTo: 'Enviar a',
    done: 'Hecho',
    deposit: 'Depositar',
    depositWarning: "Tu depósito debe enviarse en la red Monad. Tu monedero es auto-custodiado; Crystal no puede acceder a tus fondos.",
    audioNotifications: "Habilitar Notificaciones de Audio",
    connectYourWallet: "Conecta Tu Monedero",
    connectYourWalletSubtitle: "Conecta tu monedero para ver la tabla de clasificación",
    searchAMarket: "Buscar un mercado",
    browsePairs: "Explorar pares de trading",
    custom: "Personalizado",
    confirmSwap: "Confirmar Intercambio",
    highPriceImpactMessage: "¡Advertencia! ¡Alto Impacto en el Precio! Tu operación moverá el precio del mercado más del 5%",
    showTradeMarkers: "Mostrar Marcadores de Operaciones",
    usersReferred: "Usuarios Referidos",
    editUsername: "Editar Nombre de Usuario",
    bonusCommission: "Comisión de Bonificación",
    editUsernameSubtitle: "Este nombre de usuario será visible en la tabla de clasificación para todos.",
    yourWalletAddress: "Tu Dirección de Monedero",
    usernameAlreadyTaken: "Nombre de usuario ya tomado",
    minUsernameLength: "El nombre de usuario debe tener al menos 3 caracteres",
    usernameFilter: "El nombre de usuario solo puede contener letras, números y guiones bajos",
    maxUsernameLength: "El nombre de usuario debe tener menos de 20 caracteres",
    showChartOrders: "Mostrar Órdenes en Gráfico",
    bonusCommision: "Comisión de Bonificación",
    edit: "Editar",
    shareEarnText: "Comparte tu enlace de referencia con amigos y gana el 25% de sus comisiones.",
    totalUsersReferred: "Total de Usuarios Referidos",
    scaleTooltip: "Coloca múltiples órdenes límite entre un rango de precios específico en una sola transacción",
    setRefFailed: "No se pudo establecer el código de referencia, el código puede ser inválido",
    favorites: "Favoritos",
    lsts: "LSTs",
    stablecoins: "Stablecoins",
    memes: "Memes",
    pointMultiplier: "Multiplicador de Puntos",
    crystalsFromReferrals: "Crystals Por Referencias",
    refAd: "Gana hasta un 50% de reembolso en todas las comisiones con tu código de referencia",
    monadDesc: "El token nativo de la blockchain Monad, una innovadora red EVM de alto rendimiento que soporta más de 10,000 TPS.",
    wMonDesc: "Un envoltorio ERC-20 del token nativo de Monad (MON) para mayor compatibilidad con contratos inteligentes.",
    wethDesc: "Un envoltorio ERC-20 del token nativo de Ethereum (ETH) para mayor compatibilidad con contratos inteligentes.",
    wbtcDesc: "Un envoltorio ERC-20 de Bitcoin en la red Monad.",
    wsolDesc: "Un envoltorio ERC-20 del token nativo de Solana (SOL) para mayor compatibilidad con contratos inteligentes.",
    usdtDesc: "El stablecoin más ampliamente utilizado en el mundo, anclado al Dólar estadounidense en una relación 1:1.",
    smonDesc: "sMON es el Token de Staking Líquido de Kintsu en Monad, alineado con DAO, y diseñado para permitir a los usuarios ganar recompensas de staking mientras permanecen componibles en todo el ecosistema.",
    aprmonDesc: "Staking Líquido de Monad potenciado por MEV por aPriori",
    shmonDesc: "shMON: El primer Token de Staking Líquido Holístico del mundo con las mejores recompensas de staking en Monad.",
    dakDesc: "Conocido por su valentía y tradición, Molandak es el hogar de los valientes que enfrentan los desafíos de frente.",
    chogDesc: "Chog es la casa para los sabios y laboriosos que valoran el intelecto, la estrategia y la ética de trabajo incansable.",
    yakiDesc: "Moyaki nada para aquellos que surgen de orígenes humildes con un impulso inquebrantable para triunfar.",
    mintDesc: "NFT conmemorativo exclusivo para nuestros primeros usuarios de testnet. ¿Te lo perdiste? No te preocupes, ¡se viene otro drop! La elegibilidad se basará en la clasificación del leaderboard.",
    mintTitle: "Crear NFT",
    mintSubtitle: "Genera tu coleccionable digital exclusivo",
    mintCount: "Minteos",
    holders: "Poseedores",
    eligible: "Elegible",
    minted: "Minteado",
    free: "Gratis",
    minting: "Minteando…",
    hideScamWicks: "Ocultar mechas de estafa",
    alreadyMinted: "Ya acuñado",
    notEligible: "No elegible",
    loading: "Cargando...",
  },
};

type LanguageContextType = {
  language: string;
  availablelanguages: any;
  setLanguage: (lang: string) => void;
  t: (key: string) => string;
};

const LanguageContext = createContext<LanguageContextType>({
  language: 'EN',
  availablelanguages: Object.keys(translations),
  setLanguage: () => { },
  t: (key: string) => key,
});

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({
  children,
}) => {
  const [language, setLanguage] = useState(() => {
    const savedLanguage = localStorage.getItem('crystal_language');
    return savedLanguage || 'EN';
  });
  const availablelanguages = Object.keys(translations);

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider
      value={{ language, availablelanguages, setLanguage, t }}
    >
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
