import React, { createContext, useContext, useState } from 'react';

export const translations: any = {
  EN: {
    trade: 'Trade',
    connectWallet: 'Connect Wallet',
    swap: 'Swap',
    send: 'Send',
    to: 'To',
    limit: 'Limit',
    pay: 'Pay',
    receive: 'Receive',
    balance: 'Balance:',
    settings: 'Settings',
    max: 'Max',
    enterAmount: 'Enter an amount',
    insufficient: 'Insufficient ',
    swapSubtitle: 'Buy and sell any token',
    limitSubtitle: 'Trade at a specified price',
    sendSubtitle: 'Transfer tokens to anyone',
    docs: 'Documentation',
    earn: 'Earn',
    referrals: 'Referrals',
    portfolio: 'Portfolio',
    languages: 'Languages',
    networks: 'Networks',
    averagePrice: 'Average Price',
    priceImpact: 'Price Impact',
    isWorth: 'is worth',
    When: 'When',
    enterRecipient: 'Enter a recipient',
    enterWalletAddress: 'Enter wallet address',
    market: 'Market',
    Warning: 'Warning: High price impact! Your trade will move the market price by more than 5%',
    markets: 'Market',
    type: 'Type',
    size: 'Size',
    price: 'Price',
    amountFilled: 'Amount Filled',
    active: 'Active',
    time: 'Time',
    view: 'View',
    amount: 'Amount',
    all: 'All',
    buy: 'Buy',
    sell: 'Sell',
    noOpenOrders: 'No orders currently active',
    noTradeHistory: 'No trade history',
    noOrderHistory: 'No order history',
    cancelAll: 'Cancel All',
    openOrders: 'Open Orders',
    tradeHistory: 'Trade History',
    orderHistory: 'Order History',
    no: 'No',
    yes: 'Yes',
    total: 'Total',
    Spread: 'Spread',
    orderbook: 'Order Book',
    trades: 'Trades',
    availableLiquidity: 'Available Liquidity',
    dayVolume: '24hr Volume',
    dayHigh: '24hr High',
    dayLow: '24hr Low',
    dayChange: '24hr Change',
    selectAToken: 'Select a Token',
    selectTokenSubtitle: 'Select a token from our default list or find one by searching for its symbol or address.',
    searchToken: 'Search by symbol or address',
    slippage: 'Max Slippage',
    partialFill: 'Partial Fill',
    assets: 'Assets',
    USDvalue: 'USD Value',
    noWallet: "Don't have a wallet?",
    createWallet: ' Create One',
    totalAccountValue: 'Total Account Value',
    totalVolume: '24hr Volume',
    tradeValue: 'Trade Value',
    filled: 'Filled',
    canceled: 'Canceled',
    status: 'Status',
    mid: 'Mid',
    placeOrder: 'Place Order',
    avgPrice: 'Avg. Price',
    connectWalletSubtitle: 'Connect your wallet to start trading.',
    success: 'Success',
    viewOnExplorer: 'View on Explorer',
    online: 'ONLINE',
    offline: 'OFFLINE',
    twitter: 'Twitter',
    discord: 'Discord',
    beta: 'Beta',
    installed: 'Installed',
    popular: 'Popular',
    chart: 'Chart',
    copied: 'Copied',
    copyTokenAddress: 'Copy token address',
    clickCopyAddress: 'Click to copy address',
    visitTokenWebsite: 'Visit token website',
    copy: 'Copy',
    actions: 'Actions',
    graphConnectWallet: 'Connect your wallet to view your portfolio.',
    noTokensDetected: 'No tokens detected',
    performance: 'PERFORMANCE',
    balances: 'Balances',
    welcome: 'Welcome',
    portfolioValue: 'Portfolio Value',
    approve: 'Approve',
    wrap: 'Wrap',
    unwrap: 'Unwrap',
    useMarket: 'Use Market',
    onlyCurrentMarket: 'Only this market',
    limitSettings: 'Limit Settings',
    swapSettings: 'Swap Settings',
    left: 'Left',
    right: 'Right',
    customizableSubtitle: 'Customize your trading experience.',
    tradePanelPosition: 'Trade Panel Position',
    orderbookPosition: 'Orderbook Position',
    side: 'Side',
    panel: 'Panel',
    revertToDefault: 'Revert to Default',
    language: 'Language',
    referralSettings: 'Referral Settings',
    changeusedref: 'Change Used Referral',
    setRef: 'Set Referral',
    createOrViewRefLink: 'Create or View Referral Link',
    yourreflink: 'Your Referral Link',
    copyLink: 'Copy Link',
    earnings: 'Earnings',
    totalfees: 'Total Fees',
    nothingtoclaim: 'Nothing to Claim',
    claimfees: 'Claim Fees',
    simpleView: 'Simple View',
    amountFilledSubtitle: 'The amount of tokens that have been filled for this order',
    tradeValueSubtitle: 'The total value of your trade',
    statusSubtitle: 'The fill status of this order',
    signTransaction: 'Sign Transaction',
    addLiquidityOnly: 'Add Liquidity Only',
    addLiquidityOnlySubtitle: 'If enabled, ensure this order is added to the book as a maker order',
    claimTitle: 'Claim Your Earnings',
    totalClaim: 'Total Claimable',
    shareEarn: 'Share & Earn',
    customize: 'Customize',
    create: 'Create',
    noLink: 'Create a referral link to start earning!',
    communityRewards: 'Community Rewards',
    communityRewardsText: 'Earn a 25% commission and give your referred users a 25% fee discount',
    instantTracking: 'Instant Tracking',
    instantTrackingText: 'Earnings from the referral program are available to claim instantly',
    tierBenefits: 'Incentive Multipliers',
    tierBenefitsText: 'Both you and your referred users will earn more rewards',
    usingCode: 'Using Code:',
    enteracode: 'Enter referral code',
    earningsDashboard: 'Earnings Dashboard',
    earningsSubtitle: 'Track and claim your referral rewards',
    totalClaimable: 'Total Claimable',
    tokenBreakdown: 'Token Breakdown',
    availableToClaim: 'Available to claim',
    referralsHelp: 'Claim your earned fees from the referral program. Fees are collected in the token they were paid in and can be claimed anytime.',
    learnMore: 'Learn More',
    noSelfRefer: 'You cannot use your own referral code',
    customizeWarning: 'If you change your custom link, the previous one will stop working.',
    createWarning: 'Create a custom referral link',
    referralSubtitle: "Get a 25% fee discount when you use a friend or creator's referral code!",
    yourLink: 'Your referral link:',
    createCode: 'Create referral code',
    signTxn: 'Sign Transaction',
    getHelp: 'Get Help',
    totalVol: 'Total Volume',
    activeOrders: 'Active Orders',
    details: 'Details',
    account: 'ACCOUNT',
    accountSubtitle: "Overview of your wallet's recent activity",
    toggle: 'Toggle visibility of numbers',
    day: '24h',
    week: '1w',
    weektwo: '2w',
    month: '1mo',
    past: 'past',
    portValue: 'Portfolio Value',
    slippageHelp: 'The maximum percentage difference between the expected and executed price of this trade',
    averagePriceHelp: 'The estimated average execution price for this trade',
    priceImpactHelp: 'The estimated change in market price caused by this trade',
    nofeeforwrap: 'Wrapping and unwrapping ETH is 1:1 and does not incur any fees',
    takerfeeexplanation: 'Taker orders are charged a 0.02% fee',
    makerfeeexplanation: 'Maker orders are not charged any fee',
    fee: 'Fee',
    cancel: 'Cancel',
    switchto: 'Switch to',
    insufficientLiquidity: 'Insufficient Liquidity',
    insufficientLiquidityWarning: 'Warning: Insufficient liquidity. Try splitting this trade into multiple smaller orders or enabling partial fill',
    insufficientLiquidityWarningMultihop: 'Warning: Insufficient liquidity. Try splitting this trade into multiple smaller orders',
    priceOutOfRangeBuy: 'Post only price too high',
    priceOutOfRangeSell: 'Post only price too low',
    clearRef: 'Clear Referral Code',
    comingSoon: 'Coming Soon...',
    earnDesc: "We're working hard to bring you new ways to earn with your crypto. Stay tuned for updates!",
    showOB: 'Show Order Book',
    showOC: 'Show Order Center',
    priceOutOfRangeWarningBuy: 'Warning: Limit price higher than lowest ask price. This trade will likely execute as a taker order',
    priceOutOfRangeWarningSell: 'Warning: Limit price lower than highest bid price. This trade will likely execute as a taker order',
    limitPrice: 'Limit Price',
    limitPriceSubtitle: 'The price at which your order is set to execute',
    partialFillSubtitle: 'If enabled, allow partial execution if slippage is exceeded',
    sHigh: 'Session High',
    sLow: 'Session Low',
    hideBalances: 'Hide Balances',
    disconnect: 'Disconnect',
    tradingStats: 'TRADING STATS',
    refStats: 'REFERRAL STATS',
    claimableRewards: 'Claimable Rewards',
    myCode: 'My Code:',
    noCode: "Don't have a code? Create one",
    bal: 'Balance',
    landing: 'Website',
    terms: 'Terms of Use',
    view_documentation: 'Learn about Crystal',
    visit_homepage: "Visit Crystal's website",
    read_terms: 'Legal terms and conditions',
    join_community: "Join Crystal's community",
    follow_updates: "Follow Crystal's updates",
    more: 'More',
    onlyCurrentMarketHelp: 'Only display orders for this market',
    swapComplete: 'Swap Complete',
    limitComplete: 'Limit Order Complete',
    sendComplete: 'Send Complete',
    limitCancelled: 'Limit Order Cancelled',
    fillComplete: 'Order Filled',
    wrapComplete: 'Wrap Complete',
    unwrapComplete: 'Unwrap Complete',
    approveComplete: 'Approval Complete',
    basic: 'BASIC',
    pro: 'Pro',
    searchMarkets: 'Search Markets',
    clear: 'Clear',
    volume: 'Volume',
    byConnecting: "By connecting a wallet, you agree to Crystal's",
    termsOfService: 'Terms of Service',
    andConsentTo: 'and consent to its',
    privacyPolicy: 'Privacy Policy',
    enterReferralCode: 'Enter Referral Code',
    setReferral: 'Set Referral',
    clearReferralLink: 'Clear Referral Code',
    codeTaken: 'Code taken',
    invalid: 'Invalid',
    requestingConnection: 'Requesting Connection',
    confirmConnection1: 'Confirm the connection in the',
    confirmConnection2: 'browser extension to continue',
    lessThanMinSize: 'Limit order size must be >1 USDC',
    enterLimitPrice: 'Enter a limit price',
    advancedView: 'Advanced View',
    basicView: 'Basic View',
    advancedViewText: 'Master the markets',
    basicViewText: 'Trade with ease',
    noTokens: 'No tokens found',
    noMarkets: 'No markets found',
    toNavigate: 'to navigate',
    toSelect: 'to select',
    toClose: 'to close',
    pleaseEnterCode: 'Please enter a referral code',
    transactionHistory: 'Transaction History',
    search: 'Search',
    minimumSize: 'Minimum Size',
    enableFilter: 'Enable Filter',
    last: 'Last',
    scale: 'Scale',
    noTransactionsYet: 'No transactions yet',
    filledAt: 'filled at',
    start: 'Start',
    end: 'End',
    skew: 'Skew',
    orders: 'Orders',
    enterStartPrice: 'Enter a start price',
    enterEndPrice: 'Enter an end price',
    startPriceHigh: 'Start price too high',
    startPriceLow: 'Start price too low',
    endPriceHigh: 'End price too high',
    endPriceLow: 'End price too low',
    scaleMinSize: 'Smallest order size must be >1 USDC',
    enterOrders: 'Enter order count',
    enterSkew: 'Enter size skew',
    transactionDetails: 'Transaction Details',
    swapDetails: 'Swap Details',
    limitOrderDetails: 'Limit Order Details',
    sendDetails: 'Send Details',
    cancelDetails: 'Cancellation Details',
    fillDetails: 'Fill Details',
    wrapDetails: 'Wrap Details',
    unwrapDetails: 'Unwrap Details',
    approveDetails: 'Approval Details',
    generalInfo: 'Transaction Information',
    txType: 'Tx Type',
    txTime: 'Tx Time',
    txHash: 'Tx Hash',
    tokenInfo: 'Token Information',
    fromToken: 'Input Token',
    toToken: 'Output Token',
    recipientInfo: 'Recipient Information',
    contractInfo: 'Contract Information',
    address: 'Address',
    token: 'Token',
    feeInfo: 'Fee Information',
    gasUsed: 'Gas Used',
    gasPrice: 'Gas Price',
    totalFee: 'Total Fee',
    back: 'Back',
    at: 'at',
    leaderboard: 'Leaderboard',
    orderType: 'Order Type',
    editAccountTitle: "Edit Account",
    editAccountSubtitle: "Change your username and profile photo",
    username: "Username",
    chooseNewPhoto: "Choose New Photo",
    saveChanges: "Save Changes",
    viewRules: "View Rules",
    xpEarned: "XP Earned",
    rank: "Rank",
    editAccount: "Edit Account",
    createAccount: "Create Account",
    user: "User",
    totalXP: "Total XP",
    choosePhoto: "Choose Photo",
    next: "Next",
    skip: "Skip",
    complete: "Complete",
    challengeOverview: "Challenge Overview",
    learnHowToCompete: "Learn how to compete and earn rewards",
    precisionMatters: "Precision Matters",
    placeYourBids: "Place your bids toward the mid to earn bonus points",
    earnXp: "Earn XP",
    midsGiveYou: "Mids give you XP that contributes to your overall ranking",
    claimRewards: "Claim Rewards",
    competeOnLeaderboards: "Compete on the leaderboards to win prizes when the countdown ends",
    continueAsGuest: "Continue as Guest",
    getStarted: "Get Started",
    of: "of",
    page: "Page",
    viewYourPosition: "View Your Position",
    mint: "Mint",
    limitFailed: 'Limit Order Failed',
    sendFailed: 'Send Transaction Failed',
    sendingTransaction: 'Sending Transaction',

  },
  CN: {
    trade: '交易',
    connectWallet: '连接钱包',
    swap: '兑换',
    send: '发送',
    to: '至',
    limit: '限价',
    pay: '支付',
    receive: '接收',
    balance: '余额:',
    settings: '设置',
    max: '最大',
    enterAmount: '输入金额',
    insufficient: '不足 ',
    swapSubtitle: '买卖任意代币',
    limitSubtitle: '在指定价格下单',
    sendSubtitle: '向任意地址转账代币',
    docs: '文档',
    earn: '赚取',
    referrals: '推荐',
    portfolio: '资产组合',
    languages: '语言',
    networks: '网络',
    averagePrice: '平均价格',
    priceImpact: '价格影响',
    swapFee: '费用 (0.02%)',
    limitFee: '费用 (0.00%)',
    isWorth: '的价值',
    When: '当',
    enterRecipient: '输入接收人',
    enterWalletAddress: '输入钱包地址',
    market: '市场',
    Warning: '警告: 高价格影响！您的交易将使市场价格波动超过5%',
    markets: '市场',
    type: '类型',
    size: '大小',
    price: '价格',
    amountFilled: '成交量',
    active: '活跃',
    time: '时间',
    view: '查看',
    amount: '数量',
    all: '全部',
    buy: '买入',
    sell: '卖出',
    noOpenOrders: '当前无活动订单',
    noTradeHistory: '无交易历史',
    noOrderHistory: '无订单历史',
    cancelAll: '取消全部',
    openOrders: '活动订单',
    tradeHistory: '交易历史',
    orderHistory: '订单历史',
    no: '否',
    yes: '是',
    total: '总计',
    Spread: '价差',
    orderbook: '订单簿',
    trades: '交易',
    availableLiquidity: '可用流动性',
    dayVolume: '24小时交易量',
    dayHigh: '24小时最高价',
    dayLow: '24小时最低价',
    dayChange: '24小时涨跌幅',
    selectAToken: '选择代币',
    selectTokenSubtitle: '从默认列表中选择代币或通过符号或地址搜索查找。',
    searchToken: '按符号或地址搜索',
    slippage: '最大滑点',
    partialFill: '部分成交',
    assets: '资产',
    USDvalue: '美元价值',
    noWallet: '没有钱包？',
    createWallet: ' 创建一个',
    totalAccountValue: '账户总值',
    totalVolume: '24小时交易量',
    tradeValue: '交易额',
    filled: '已成交',
    canceled: '已取消',
    status: '状态',
    mid: '中值',
    placeOrder: '下单',
    avgPrice: '平均价',
    connectWalletSubtitle: '连接您的钱包开始交易。',
    success: '成功',
    viewOnExplorer: '在区块链浏览器查看',
    online: '在线',
    offline: '离线',
    twitter: 'Twitter',
    discord: 'Discord',
    beta: '测试版',
    installed: '已安装',
    popular: '热门',
    chart: '图表',
    copied: '已复制',
    copyTokenAddress: '复制代币地址',
    clickCopyAddress: '点击复制地址',
    visitTokenWebsite: '访问代币官网',
    copy: '复制',
    actions: '操作',
    graphConnectWallet: '连接您的钱包查看资产组合。',
    noTokensDetected: '未检测到代币',
    performance: '表现',
    balances: '余额',
    welcome: '欢迎',
    portfolioValue: '资产组合价值',
    approve: '批准',
    wrap: '包装',
    unwrap: '解包',
    useMarket: '使用市场',
    onlyCurrentMarket: '仅此市场',
    limitSettings: '限价设置',
    swapSettings: '兑换设置',
    left: '左侧',
    right: '右侧',
    customizableSubtitle: '自定义您的交易体验。',
    tradePanelPosition: '交易面板位置',
    orderbookPosition: '订单簿位置',
    side: '方向',
    panel: '面板',
    revertToDefault: '恢复默认',
    language: '语言',
    referralSettings: '推荐设置',
    changeusedref: '更改使用的推荐码',
    setRef: '设置推荐码',
    createOrViewRefLink: '创建或查看推荐链接',
    yourreflink: '您的推荐链接',
    copyLink: '复制链接',
    earnings: '收益',
    totalfees: '总费用',
    nothingtoclaim: '无可领取',
    claimfees: '领取费用',
    simpleView: '简单视图',
    amountFilledSubtitle: '订单成交的代币数量',
    tradeValueSubtitle: '交易总额',
    statusSubtitle: '订单成交状态',
    signTransaction: '签名交易',
    addLiquidityOnly: '仅添加流动性',
    addLiquidityOnlySubtitle: '启用后，确保此订单以挂单方式加入订单簿',
    claimTitle: '领取您的收益',
    totalClaim: '总可领取金额',
    shareEarn: '分享 & 赚取',
    customize: '自定义',
    create: '创建',
    noLink: '创建推荐链接以开始赚取！',
    communityRewards: '社区奖励',
    communityRewardsText: '赚取25%佣金，并给予推荐用户25%费用折扣',
    instantTracking: '即时追踪',
    instantTrackingText: '推荐计划收益可立即领取',
    tierBenefits: '激励倍增',
    tierBenefitsText: '您和推荐用户将获得更多奖励',
    usingCode: '使用代码:',
    enteracode: '输入推荐代码',
    earningsDashboard: '收益仪表盘',
    earningsSubtitle: '追踪并领取推荐奖励',
    totalClaimable: '总可领取',
    tokenBreakdown: '代币分解',
    availableToClaim: '可领取',
    referralsHelp: '领取推荐计划中获得的费用，费用以支付代币形式收取，随时可领。',
    learnMore: '了解更多',
    noSelfRefer: '不能使用自己的推荐码',
    customizeWarning: '更改自定义链接将使之前的链接失效。',
    createWarning: '创建自定义推荐链接',
    referralSubtitle: '使用好友或创作者推荐码可享25%费用折扣！',
    yourLink: '您的推荐链接:',
    createCode: '创建推荐码',
    signTxn: '签名交易',
    getHelp: '获取帮助',
    totalVol: '总交易量',
    activeOrders: '活动订单',
    details: '详情',
    account: '账户',
    accountSubtitle: '钱包近期活动概览',
    toggle: '切换数字显示',
    day: '24小时',
    week: '1周',
    weektwo: '2周',
    month: '1月',
    past: '过去',
    portValue: '组合价值',
    slippageHelp: '预期与执行价格最大百分比差',
    averagePriceHelp: '预计平均执行价格',
    priceImpactHelp: '交易对市场价格影响预估',
    nofeeforwrap: 'ETH包装/解包1:1，无费用',
    takerfeeexplanation: '接受订单收取0.02%费用',
    makerfeeexplanation: '挂单无费用',
    fee: '费用',
    cancel: '取消',
    switchto: '切换到',
    insufficientLiquidity: '流动性不足',
    insufficientLiquidityWarning: '警告: 流动性不足。尝试拆分订单或启用部分成交',
    insufficientLiquidityWarningMultihop: '警告: 流动性不足。尝试拆分订单',
    priceOutOfRangeBuy: '挂单价格过高',
    priceOutOfRangeSell: '挂单价格过低',
    clearRef: '清除推荐码',
    comingSoon: '即将推出...',
    earnDesc: '我们正在努力提供更多加密收益方式，敬请期待！',
    showOB: '显示订单簿',
    showOC: '显示订单中心',
    priceOutOfRangeWarningBuy: '警告: 限价高于最低卖价，可能作为接受订单执行',
    priceOutOfRangeWarningSell: '警告: 限价低于最高买价，可能作为接受订单执行',
    limitPrice: '限价',
    limitPriceSubtitle: '订单执行价格',
    partialFillSubtitle: '启用后，允许部分成交',
    sHigh: '本场最高',
    sLow: '本场最低',
    hideBalances: '隐藏余额',
    disconnect: '断开连接',
    tradingStats: '交易统计',
    refStats: '推荐统计',
    claimableRewards: '可领取奖励',
    myCode: '我的代码:',
    noCode: "没有代码？创建一个",
    bal: '余额',
    landing: '官网',
    terms: '条款',
    view_documentation: '了解 Crystal',
    visit_homepage: "访问 Crystal 官网",
    read_terms: '法律条款与条件',
    join_community: '加入 Crystal 社区',
    follow_updates: '关注 Crystal 更新',
    more: '更多',
    onlyCurrentMarketHelp: '仅显示此市场订单',
    swapComplete: '兑换完成',
    limitComplete: '限价订单完成',
    sendComplete: '发送完成',
    limitCancelled: '限价订单已取消',
    fillComplete: '订单已成交',
    wrapComplete: '包装完成',
    unwrapComplete: '解包完成',
    approveComplete: '批准完成',
    basic: '基础',
    pro: '专业',
    searchMarkets: '搜索市场',
    clear: '清除',
    volume: '成交量',
    byConnecting: '连接钱包即表示您同意 Crystal 的',
    termsOfService: '服务条款',
    andConsentTo: '并同意其',
    privacyPolicy: '隐私政策',
    enterReferralCode: '输入推荐码',
    setReferral: '设置推荐码',
    clearReferralLink: '清除推荐码',
    codeTaken: '代码已被占用',
    invalid: '无效',
    requestingConnection: '请求连接中',
    confirmConnection1: '请在',
    confirmConnection2: '浏览器扩展中确认连接以继续',
    lessThanMinSize: '限价订单数量必须大于1 USDC',
    enterLimitPrice: '输入限价',
    advancedView: '高级视图',
    basicView: '基础视图',
    advancedViewText: '掌握市场',
    basicViewText: '轻松交易',
    noTokens: '未找到代币',
    noMarkets: '未找到市场',
    toNavigate: '以导航',
    toSelect: '以选择',
    toClose: '以关闭',
    pleaseEnterCode: '请输入推荐码',
    transactionHistory: '交易历史',
    search: '搜索',
    minimumSize: '最小数量',
    enableFilter: '启用筛选',
    noTransactionsYet: '暂无交易',
    start: '开始',
    filledAt: '成交于',
    end: '结束',
    skew: '倾斜',
    orders: '订单',
    enterStartPrice: '输入起始价格',
    enterEndPrice: '输入结束价格',
    startPriceHigh: '起始价格过高',
    startPriceLow: '起始价格过低',
    endPriceHigh: '结束价格过高',
    endPriceLow: '结束价格过低',
    scaleMinSize: '最小订单规模必须大于1 USDC',
    enterOrders: '输入订单数量',
    enterSkew: '输入规模倾斜',
    transactionDetails: '交易详情',
    swapDetails: '兑换详情',
    limitOrderDetails: '限价订单详情',
    sendDetails: '发送详情',
    cancelDetails: '取消详情',
    fillDetails: '成交详情',
    wrapDetails: '包装详情',
    unwrapDetails: '解包详情',
    approveDetails: '批准详情',
    generalInfo: '基本信息',
    txType: '交易类型',
    txTime: '交易时间',
    txHash: '交易哈希',
    tokenInfo: '代币信息',
    fromToken: '来源代币',
    toToken: '目标代币',
    recipientInfo: '接收方信息',
    contractInfo: '合约信息',
    address: '地址',
    token: '代币',
    feeInfo: '费用信息',
    gasUsed: '使用的 Gas',
    gasPrice: 'Gas 价格',
    totalFee: '总费用',
    back: '返回',
    at: '价格',
    leaderboard: '排行榜',
    scale: '规模',
    orderType: '订单类型',
    editAccountTitle: "编辑账户",
    editAccountSubtitle: "更改您的用户名和个人照片",
    username: "用户名",
    chooseNewPhoto: "选择新照片",
    saveChanges: "保存更改",
    viewRules: "查看规则",
    xpEarned: "获得的经验值",
    rank: "排名",
    editAccount: "编辑账户",
    createAccount: "创建账户",
    user: "用户",
    totalXP: "总经验值",
    choosePhoto: "选择照片",
    next: "下一步",
    skip: "跳过",
    complete: "完成",
    challengeOverview: "挑战概览",
    learnHowToCompete: "了解如何竞争并获得奖励",
    precisionMatters: "精确很重要",
    placeYourBids: "将您的出价定在中间以赚取奖励积分",
    earnXp: "获取经验值",
    midsGiveYou: "中间价给您提供经验值，有助于您的整体排名",
    claimRewards: "领取奖励",
    competeOnLeaderboards: "在排行榜上竞争，在倒计时结束时赢取奖品",
    continueAsGuest: "以访客身份继续",
    getStarted: "开始使用",
    of: "的",
    page: "页",
    viewYourPosition: "查看您的排名",
    mint: "铸造",
    limitFailed: '限价订单失败',
    sendingTransaction: '发送交易',
 
  },
  JP: {
    trade: '取引',
    connectWallet: 'ウォレットを接続',
    swap: 'スワップ',
    send: '送信',
    to: 'へ',
    limit: '指値',
    pay: '支払う',
    receive: '受取',
    balance: '残高:',
    settings: '設定',
    max: '最大',
    enterAmount: '金額を入力',
    insufficient: '不足',
    swapSubtitle: '任意のトークンを売買',
    limitSubtitle: '指定価格で取引',
    sendSubtitle: '誰にでもトークンを送信',
    docs: 'ドキュメント',
    earn: '獲得',
    referrals: '紹介',
    portfolio: 'ポートフォリオ',
    languages: '言語',
    networks: 'ネットワーク',
    averagePrice: '平均価格',
    priceImpact: '価格影響',
    swapFee: '手数料 (0.02%)',
    limitFee: '手数料 (0.00%)',
    isWorth: 'の価値がある',
    When: 'いつ',
    enterRecipient: '受取人を入力',
    enterWalletAddress: 'ウォレットアドレスを入力',
    market: 'マーケット',
    Warning: '警告: 価格影響が大きいです！取引により市場価格が5%以上変動します',
    markets: 'マーケット',
    type: 'タイプ',
    size: 'サイズ',
    price: '価格',
    amountFilled: '約定量',
    active: 'アクティブ',
    time: '時間',
    view: '表示',
    amount: '数量',
    all: 'すべて',
    buy: '買い',
    sell: '売り',
    noOpenOrders: '現在、注文はありません',
    noTradeHistory: '取引履歴なし',
    noOrderHistory: '注文履歴なし',
    cancelAll: '全キャンセル',
    openOrders: 'オープン注文',
    tradeHistory: '取引履歴',
    orderHistory: '注文履歴',
    no: 'いいえ',
    yes: 'はい',
    total: '合計',
    Spread: 'スプレッド',
    orderbook: 'オーダーブック',
    trades: '取引',
    availableLiquidity: '利用可能流動性',
    dayVolume: '24時間出来高',
    dayHigh: '24時間高値',
    dayLow: '24時間安値',
    dayChange: '24時間変動',
    selectAToken: 'トークンを選択',
    selectTokenSubtitle: 'デフォルトリストから選ぶか、シンボル/アドレスで検索',
    searchToken: 'シンボル/アドレスで検索',
    slippage: '最大スリッページ',
    partialFill: '部分約定',
    assets: '資産',
    USDvalue: 'USD価値',
    noWallet: 'ウォレットがありませんか？',
    createWallet: ' 作成する',
    totalAccountValue: 'アカウント総額',
    totalVolume: '24時間出来高',
    tradeValue: '取引額',
    filled: '約定済み',
    canceled: 'キャンセル済み',
    status: 'ステータス',
    mid: 'ミッド',
    placeOrder: '注文する',
    avgPrice: '平均価格',
    connectWalletSubtitle: 'ウォレットを接続して取引開始',
    success: '成功',
    viewOnExplorer: 'エクスプローラーで確認',
    online: 'オンライン',
    offline: 'オフライン',
    twitter: 'Twitter',
    discord: 'Discord',
    beta: 'ベータ',
    installed: 'インストール済み',
    popular: '人気',
    chart: 'チャート',
    copied: 'コピー済み',
    copyTokenAddress: 'トークンアドレスをコピー',
    clickCopyAddress: 'クリックしてコピー',
    visitTokenWebsite: 'トークンサイトへ',
    copy: 'コピー',
    actions: '操作',
    graphConnectWallet: 'ポートフォリオ表示のためウォレット接続',
    noTokensDetected: 'トークンが見つかりません',
    performance: 'パフォーマンス',
    balances: '残高',
    welcome: 'ようこそ',
    portfolioValue: 'ポートフォリオ価値',
    approve: '承認',
    wrap: 'ラップ',
    unwrap: 'アンラップ',
    useMarket: 'マーケット利用',
    onlyCurrentMarket: 'このマーケットのみ',
    limitSettings: '指値設定',
    swapSettings: 'スワップ設定',
    left: '左',
    right: '右',
    customizableSubtitle: '取引体験をカスタマイズ',
    tradePanelPosition: '取引パネル位置',
    orderbookPosition: 'オーダーブック位置',
    side: 'サイド',
    panel: 'パネル',
    revertToDefault: 'デフォルトに戻す',
    language: '言語',
    referralSettings: 'リファラル設定',
    changeusedref: '使用中のリファラル変更',
    setRef: 'リファラル設定',
    createOrViewRefLink: 'リファラルリンク作成/表示',
    yourreflink: 'あなたのリファラルリンク',
    copyLink: 'リンクコピー',
    earnings: '収益',
    totalfees: '総手数料',
    nothingtoclaim: '請求可能なし',
    claimfees: '手数料請求',
    simpleView: 'シンプルビュー',
    amountFilledSubtitle: 'この注文で約定した数量',
    tradeValueSubtitle: '取引総額',
    statusSubtitle: '注文約定状況',
    signTransaction: '取引に署名',
    addLiquidityOnly: '流動性追加のみ',
    addLiquidityOnlySubtitle: '有効ならメーカー注文として追加',
    claimTitle: '収益を請求',
    totalClaim: '請求可能総額',
    shareEarn: 'シェア＆獲得',
    customize: 'カスタマイズ',
    create: '作成',
    noLink: 'リファラルリンクを作成して稼ごう！',
    communityRewards: 'コミュニティ報酬',
    communityRewardsText: '25%コミッション＆25%手数料割引',
    instantTracking: '即時追跡',
    instantTrackingText: 'リファラル収益は即時請求可能',
    tierBenefits: 'インセンティブ倍率',
    tierBenefitsText: 'あなたと紹介者がより多く獲得',
    usingCode: 'コード使用:',
    enteracode: 'リファラルコード入力',
    earningsDashboard: '収益ダッシュボード',
    earningsSubtitle: 'リファラル報酬を追跡・請求',
    totalClaimable: '請求可能総額',
    tokenBreakdown: 'トークン内訳',
    availableToClaim: '請求可能',
    referralsHelp: 'リファラル報酬をいつでも請求可能',
    learnMore: '詳細を見る',
    noSelfRefer: '自分のコードは不可',
    customizeWarning: 'カスタムリンク変更で旧リンク無効',
    createWarning: 'カスタムリファラルリンク作成',
    referralSubtitle: '友達/クリエイターコードで25%割引！',
    yourLink: 'あなたのリンク:',
    createCode: 'リファラルコード作成',
    signTxn: '取引署名',
    getHelp: 'ヘルプ取得',
    totalVol: '総出来高',
    activeOrders: 'アクティブ注文',
    details: '詳細',
    account: 'アカウント',
    accountSubtitle: 'ウォレット最近の活動',
    toggle: '数字表示切替',
    day: '24h',
    week: '1w',
    weektwo: '2w',
    month: '1mo',
    past: '過去',
    portValue: 'ポートフォリオ価値',
    slippageHelp: '期待値と実績の最大乖離率',
    averagePriceHelp: '推定平均実行価格',
    priceImpactHelp: '取引が市場に与える影響',
    nofeeforwrap: 'ETHラップ/アンラップ1:1、手数料なし',
    takerfeeexplanation: 'テイカー0.02%手数料',
    makerfeeexplanation: 'メイカー手数料なし',
    fee: '手数料',
    cancel: 'キャンセル',
    switchto: '切替',
    insufficientLiquidity: '流動性不足',
    insufficientLiquidityWarning: '警告: 流動性不足。小分け注文または部分約定を検討',
    insufficientLiquidityWarningMultihop: '警告: 流動性不足。注文を小分けに',
    priceOutOfRangeBuy: '買注文価格過高',
    priceOutOfRangeSell: '売注文価格過低',
    clearRef: 'リファラル削除',
    comingSoon: '近日公開...',
    earnDesc: '新たな収益方法を準備中。更新をお待ちください！',
    showOB: 'オーダーブック表示',
    showOC: '注文センター表示',
    priceOutOfRangeWarningBuy: '警告: 指値が最低売値超。テイカー扱いの可能性',
    priceOutOfRangeWarningSell: '警告: 指値が最高買値下。テイカー扱いの可能性',
    limitPrice: '指値',
    limitPriceSubtitle: '注文実行価格',
    partialFillSubtitle: '超過時、部分約定を許可',
    sHigh: 'セッション高値',
    sLow: 'セッション安値',
    hideBalances: '残高非表示',
    disconnect: '切断',
    tradingStats: '取引統計',
    refStats: 'リファラル統計',
    claimableRewards: '請求可能報酬',
    myCode: '私のコード:',
    noCode: 'コード未作成',
    bal: '残高',
    landing: 'ウェブサイト',
    terms: '利用規約',
    view_documentation: 'Crystalについて学ぶ',
    visit_homepage: "Crystalのサイトへ",
    read_terms: '法的条件',
    join_community: 'Crystalコミュニティ参加',
    follow_updates: 'Crystal更新をフォロー',
    more: 'もっと見る',
    onlyCurrentMarketHelp: 'このマーケットのみ表示',
    swapComplete: 'スワップ完了',
    limitComplete: '指値完了',
    sendComplete: '送信完了',
    limitCancelled: '指値キャンセル',
    fillComplete: '約定完了',
    wrapComplete: 'ラップ完了',
    unwrapComplete: 'アンラップ完了',
    approveComplete: '承認完了',
    basic: 'BASIC',
    pro: 'PRO',
    searchMarkets: 'マーケット検索',
    clear: 'クリア',
    volume: '出来高',
    byConnecting: 'ウォレット接続でCrystalの',
    termsOfService: '利用規約',
    andConsentTo: 'に同意',
    privacyPolicy: 'プライバシー',
    enterReferralCode: 'リファラルコード入力',
    setReferral: 'リファラル設定',
    clearReferralLink: 'リファラル削除',
    codeTaken: 'コード使用中',
    invalid: '無効',
    requestingConnection: '接続要求中',
    confirmConnection1: '拡張で',
    confirmConnection2: 'の接続を確認してください',
    lessThanMinSize: '注文サイズは1 USDC以上',
    enterLimitPrice: '指値入力',
    advancedView: 'アドバンスドビュー',
    basicView: 'ベーシックビュー',
    advancedViewText: '市場を制する',
    basicViewText: '簡単に取引',
    noTokens: 'トークン未検出',
    noMarkets: 'マーケット未検出',
    toNavigate: '移動するには',
    toSelect: '選ぶには',
    toClose: '閉じるには',
    pleaseEnterCode: 'リファラルコード入力を',
    transactionHistory: '取引履歴',
    filledAt: '約定価格',
    start: '開始',
    end: '終了',
    skew: '偏り',
    orders: '注文',
    enterStartPrice: '開始価格を入力',
    enterEndPrice: '終了価格を入力',
    startPriceHigh: '開始価格が高すぎます',
    startPriceLow: '開始価格が低すぎます',
    endPriceHigh: '終了価格が高すぎます',
    endPriceLow: '終了価格が低すぎます',
    scaleMinSize: '最小注文サイズは1 USDC以上必要です',
    enterOrders: '注文数を入力',
    enterSkew: 'サイズ偏りを入力',
    search: '検索',
    minimumSize: '最小サイズ',
    enableFilter: 'フィルター有効',
    noTransactionsYet: '取引なし',
    transactionDetails: '取引詳細',
    swapDetails: 'スワップ詳細',
    limitOrderDetails: '指値注文詳細',
    sendDetails: '送信詳細',
    cancelDetails: 'キャンセル詳細',
    fillDetails: '約定詳細',
    wrapDetails: 'ラップ詳細',
    unwrapDetails: 'アンラップ詳細',
    approveDetails: '承認詳細',
    generalInfo: '一般情報',
    txType: '取引タイプ',
    txTime: '取引時間',
    txHash: '取引ハッシュ',
    tokenInfo: 'トークン情報',
    fromToken: '送信元トークン',
    toToken: '送信先トークン',
    recipientInfo: '受取人情報',
    contractInfo: 'コントラクト情報',
    address: 'アドレス',
    token: 'トークン',
    feeInfo: '手数料情報',
    gasUsed: '使用ガス',
    gasPrice: 'ガス価格',
    totalFee: '合計手数料',
    back: '戻る',
    at: '価格',
    leaderboard: 'リーダーボード',
    scale: 'スケール',
    orderType: '注文タイプ',
    editAccountTitle: "アカウント編集",
    editAccountSubtitle: "ユーザー名とプロフィール写真を変更する",
    username: "ユーザー名",
    chooseNewPhoto: "新しい写真を選択",
    saveChanges: "変更を保存",
    viewRules: "ルールを表示",
    xpEarned: "獲得XP",
    rank: "ランク",
    editAccount: "アカウント編集",
    createAccount: "アカウント作成",
    user: "ユーザー",
    totalXP: "合計XP",
    choosePhoto: "写真を選択",
    next: "次へ",
    skip: "スキップ",
    complete: "完了",
    challengeOverview: "チャレンジ概要",
    learnHowToCompete: "競争方法と報酬獲得方法を学ぶ",
    precisionMatters: "精度が重要",
    placeYourBids: "中間値に向けて入札し、ボーナスポイントを獲得",
    earnXp: "XPを獲得",
    midsGiveYou: "中間値はあなたの総合ランキングに貢献するXPを提供します",
    claimRewards: "報酬を請求",
    competeOnLeaderboards: "リーダーボードで競い、カウントダウン終了時に賞品を獲得",
    continueAsGuest: "ゲストとして続ける",
    getStarted: "始める",
    of: "の",
    page: "ページ",
    viewYourPosition: "あなたの位置を表示",
    mint: "鋳造",
    limitFailed: '指値注文失敗',
    sendingTransaction: '取引送信中',

  },
  KR: {
    trade: '거래',
    connectWallet: '지갑 연결',
    swap: '스왑',
    send: '전송',
    to: '에게',
    limit: '지정가',
    pay: '지불',
    receive: '수신',
    balance: '잔액:',
    settings: '설정',
    max: '최대',
    enterAmount: '금액 입력',
    insufficient: '부족 ',
    swapSubtitle: '모든 토큰을 매매하세요',
    limitSubtitle: '지정가로 거래하세요',
    sendSubtitle: '누구에게나 토큰 전송',
    docs: '문서',
    earn: '수익',
    referrals: '추천',
    portfolio: '포트폴리오',
    languages: '언어',
    networks: '네트워크',
    averagePrice: '평균 가격',
    priceImpact: '가격 영향',
    swapFee: '수수료 (0.02%)',
    limitFee: '수수료 (0.00%)',
    isWorth: '의 가치',
    When: '언제',
    enterRecipient: '수신자 입력',
    enterWalletAddress: '지갑 주소 입력',
    market: '시장',
    Warning: '경고: 높은 가격 영향! 거래로 인해 시장 가격이 5% 이상 변동할 수 있습니다',
    markets: '시장',
    type: '유형',
    size: '크기',
    price: '가격',
    amountFilled: '체결량',
    active: '활성',
    time: '시간',
    view: '보기',
    amount: '수량',
    all: '전체',
    buy: '매수',
    sell: '매도',
    noOpenOrders: '활성 주문이 없습니다',
    noTradeHistory: '거래 내역 없음',
    noOrderHistory: '주문 내역 없음',
    cancelAll: '전체 취소',
    openOrders: '미체결 주문',
    tradeHistory: '거래 내역',
    orderHistory: '주문 내역',
    no: '아니오',
    yes: '예',
    total: '총계',
    Spread: '스프레드',
    orderbook: '오더북',
    trades: '거래',
    availableLiquidity: '사용 가능 유동성',
    dayVolume: '24시간 거래량',
    dayHigh: '24시간 최고가',
    dayLow: '24시간 최저가',
    dayChange: '24시간 변화',
    selectAToken: '토큰 선택',
    selectTokenSubtitle: '기본 목록에서 선택하거나 심볼/주소로 검색하세요',
    searchToken: '심볼/주소 검색',
    slippage: '최대 슬리피지',
    partialFill: '부분 체결',
    assets: '자산',
    USDvalue: 'USD 가치',
    noWallet: '지갑이 없으신가요?',
    createWallet: ' 지갑 만들기',
    totalAccountValue: '총 계좌 가치',
    totalVolume: '24시간 거래량',
    tradeValue: '거래 금액',
    filled: '체결됨',
    canceled: '취소됨',
    status: '상태',
    mid: '중간가',
    placeOrder: '주문하기',
    avgPrice: '평균가',
    connectWalletSubtitle: '지갑 연결 후 거래 시작하세요',
    success: '성공',
    viewOnExplorer: '익스플로러에서 보기',
    online: '온라인',
    offline: '오프라인',
    twitter: 'Twitter',
    discord: 'Discord',
    beta: '베타',
    installed: '설치됨',
    popular: '인기',
    chart: '차트',
    copied: '복사됨',
    copyTokenAddress: '토큰 주소 복사',
    clickCopyAddress: '주소를 복사하려면 클릭',
    visitTokenWebsite: '토큰 사이트 방문',
    copy: '복사',
    actions: '액션',
    graphConnectWallet: '포트폴리오 확인을 위해 지갑 연결',
    noTokensDetected: '토큰 감지 안됨',
    performance: '실적',
    balances: '잔액',
    welcome: '환영합니다',
    portfolioValue: '포트폴리오 가치',
    approve: '승인',
    wrap: '랩',
    unwrap: '언랩',
    useMarket: '마켓 사용',
    onlyCurrentMarket: '현재 마켓만',
    limitSettings: '지정가 설정',
    swapSettings: '스왑 설정',
    left: '왼쪽',
    right: '오른쪽',
    customizableSubtitle: '거래 경험 맞춤 설정',
    tradePanelPosition: '거래 패널 위치',
    orderbookPosition: '오더북 위치',
    side: '측면',
    panel: '패널',
    revertToDefault: '기본값 복원',
    language: '언어',
    referralSettings: '추천 설정',
    changeusedref: '사용 중 추천 변경',
    setRef: '추천 설정',
    createOrViewRefLink: '추천 링크 생성/보기',
    yourreflink: '당신의 추천 링크',
    copyLink: '링크 복사',
    earnings: '수익',
    totalfees: '총 수수료',
    nothingtoclaim: '청구 없음',
    claimfees: '수수료 청구',
    simpleView: '심플 뷰',
    amountFilledSubtitle: '이 주문 체결 토큰 수',
    tradeValueSubtitle: '거래 총액',
    statusSubtitle: '주문 체결 상태',
    signTransaction: '거래 서명',
    addLiquidityOnly: '유동성 추가만',
    addLiquidityOnlySubtitle: '활성 시 메이커 주문으로 추가',
    claimTitle: '수익 청구',
    totalClaim: '청구 가능 총액',
    shareEarn: '공유 & 수익',
    customize: '맞춤 설정',
    create: '생성',
    noLink: '추천 링크 생성 후 수익 시작!',
    communityRewards: '커뮤니티 보상',
    communityRewardsText: '25% 커미션 및 추천자 25% 할인',
    instantTracking: '즉시 추적',
    instantTrackingText: '추천 수익 즉시 청구 가능',
    tierBenefits: '인센티브 배수',
    tierBenefitsText: '추천자와 함께 더 많은 보상',
    usingCode: '코드 사용:',
    enteracode: '추천 코드 입력',
    earningsDashboard: '수익 대시보드',
    earningsSubtitle: '추천 보상 추적 및 청구',
    totalClaimable: '총 청구 가능액',
    tokenBreakdown: '토큰 내역',
    availableToClaim: '청구 가능',
    referralsHelp: '추천 프로그램 수수료를 언제든 청구하세요.',
    learnMore: '자세히 보기',
    noSelfRefer: '자신의 추천 코드는 사용 불가',
    customizeWarning: '맞춤 링크 변경 시 기존 링크 무효',
    createWarning: '맞춤 추천 링크 생성',
    referralSubtitle: '친구 추천 시 25% 할인!',
    yourLink: '당신의 링크:',
    createCode: '추천 코드 생성',
    signTxn: '거래 서명',
    getHelp: '도움 받기',
    totalVol: '총 거래량',
    activeOrders: '활성 주문',
    details: '세부사항',
    account: '계정',
    accountSubtitle: '지갑 최근 활동 개요',
    toggle: '숫자 표시 전환',
    day: '24시간',
    week: '1주',
    weektwo: '2주',
    month: '1개월',
    past: '과거',
    portValue: '포트폴리오 가치',
    slippageHelp: '예상과 실행 가격 차 (%)',
    averagePriceHelp: '예상 평균 실행 가격',
    priceImpactHelp: '거래가 가격에 미치는 영향',
    nofeeforwrap: 'ETH 랩/언랩 1:1, 수수료 없음',
    takerfeeexplanation: '테이커 0.02% 수수료',
    makerfeeexplanation: '메이커 수수료 없음',
    fee: '수수료',
    cancel: '취소',
    switchto: '전환',
    insufficientLiquidity: '유동성 부족',
    insufficientLiquidityWarning: '경고: 유동성 부족. 주문 분할 또는 부분 체결 고려',
    insufficientLiquidityWarningMultihop: '경고: 유동성 부족. 주문을 분할하세요',
    priceOutOfRangeBuy: '매수 가격 초과',
    priceOutOfRangeSell: '매도 가격 미달',
    clearRef: '추천 코드 삭제',
    comingSoon: '곧 출시 예정...',
    earnDesc: '새로운 암호화 수익 방식 준비 중입니다. 업데이트 기대!',
    showOB: '오더북 표시',
    showOC: '주문 센터 표시',
    priceOutOfRangeWarningBuy: '경고: 지정가가 최저 매도가 초과, 테이커 가능',
    priceOutOfRangeWarningSell: '경고: 지정가가 최고 매수가 미달, 테이커 가능',
    limitPrice: '지정가',
    limitPriceSubtitle: '주문 실행 가격',
    partialFillSubtitle: '슬리피지 초과 시 부분 체결 허용',
    sHigh: '세션 최고가',
    sLow: '세션 최저가',
    hideBalances: '잔액 숨기기',
    disconnect: '연결 해제',
    tradingStats: '거래 통계',
    refStats: '추천 통계',
    claimableRewards: '청구 가능 보상',
    myCode: '내 코드:',
    noCode: '코드 없음, 생성하세요',
    bal: '잔액',
    landing: '웹사이트',
    terms: '이용 약관',
    view_documentation: 'Crystal 정보 보기',
    visit_homepage: 'Crystal 사이트 방문',
    read_terms: '법적 약관',
    join_community: 'Crystal 커뮤니티 가입',
    follow_updates: 'Crystal 업데이트 팔로우',
    more: '더 보기',
    onlyCurrentMarketHelp: '현재 시장 주문만 표시',
    swapComplete: '스왑 완료',
    limitComplete: '지정가 완료',
    sendComplete: '전송 완료',
    limitCancelled: '지정가 취소됨',
    fillComplete: '주문 체결 완료',
    wrapComplete: '랩 완료',
    unwrapComplete: '언랩 완료',
    approveComplete: '승인 완료',
    basic: '베이직',
    pro: '프로',
    searchMarkets: '시장 검색',
    clear: '지우기',
    volume: '거래량',
    byConnecting: '지갑 연결 시, Crystal의',
    termsOfService: '이용 약관',
    andConsentTo: '및 동의',
    privacyPolicy: '개인정보 처리방침',
    enterReferralCode: '추천 코드 입력',
    setReferral: '추천 설정',
    clearReferralLink: '추천 코드 삭제',
    codeTaken: '코드 사용 중',
    invalid: '유효하지 않음',
    requestingConnection: '연결 요청 중',
    confirmConnection1: '확인을 위해 브라우저 확장에서',
    confirmConnection2: '연결 승인 바랍니다',
    lessThanMinSize: '주문 크기는 1 USDC 이상',
    enterLimitPrice: '지정가 입력',
    advancedView: '고급 보기',
    basicView: '기본 보기',
    advancedViewText: '시장을 마스터하세요',
    basicViewText: '쉽게 거래하세요',
    noTokens: '토큰 없음',
    noMarkets: '시장 없음',
    toNavigate: '이동하려면',
    toSelect: '선택하려면',
    toClose: '닫으려면',
    pleaseEnterCode: '추천 코드 입력하세요',
    transactionHistory: '거래 내역',
    search: '검색',
    minimumSize: '최소 크기',
    enableFilter: '필터 활성',
    noTransactionsYet: '아직 거래 없음',
    filledAt: '체결 가격',
    start: '시작',
    end: '종료',
    skew: '치우침',
    orders: '주문',
    enterStartPrice: '시작 가격 입력',
    enterEndPrice: '종료 가격 입력',
    startPriceHigh: '시작 가격이 너무 높음',
    startPriceLow: '시작 가격이 너무 낮음',
    endPriceHigh: '종료 가격이 너무 높음',
    endPriceLow: '종료 가격이 너무 낮음',
    scaleMinSize: '최소 주문 크기는 1 USDC 이상이어야 함',
    enterOrders: '주문 수량 입력',
    enterSkew: '크기 치우침 입력',
    transactionDetails: '거래 상세',
    swapDetails: '스왑 상세',
    limitOrderDetails: '지정가 주문 상세',
    sendDetails: '전송 상세',
    cancelDetails: '취소 상세',
    fillDetails: '체결 상세',
    wrapDetails: '랩 상세',
    unwrapDetails: '언랩 상세',
    approveDetails: '승인 상세',
    generalInfo: '기본 정보',
    txType: '거래 유형',
    txTime: '거래 시간',
    txHash: '거래 해시',
    tokenInfo: '토큰 정보',
    fromToken: '출발 토큰',
    toToken: '도착 토큰',
    recipientInfo: '수신자 정보',
    contractInfo: '컨트랙트 정보',
    address: '주소',
    token: '토큰',
    feeInfo: '수수료 정보',
    gasUsed: '사용된 가스',
    gasPrice: '가스 가격',
    totalFee: '총 수수료',
    back: '뒤로',
    at: '가격',
    leaderboard: '리더보드',
    scale: '스케일',
    orderType: '주문 유형',
    editAccountTitle: "계정 편집",
    editAccountSubtitle: "사용자 이름 및 프로필 사진 변경",
    username: "사용자 이름",
    chooseNewPhoto: "새 사진 선택",
    saveChanges: "변경 사항 저장",
    viewRules: "규칙 보기",
    xpEarned: "획득한 XP",
    rank: "순위",
    editAccount: "계정 편집",
    createAccount: "계정 만들기",
    user: "사용자",
    totalXP: "총 XP",
    choosePhoto: "사진 선택",
    next: "다음",
    skip: "건너뛰기",
    complete: "완료",
    challengeOverview: "챌린지 개요",
    learnHowToCompete: "경쟁하고 보상을 얻는 방법 알아보기",
    precisionMatters: "정확성이 중요합니다",
    placeYourBids: "중간값에 입찰하여 보너스 포인트 획득",
    earnXp: "XP 획득",
    midsGiveYou: "중간값은 전체 순위에 기여하는 XP를 제공합니다",
    claimRewards: "보상 받기",
    competeOnLeaderboards: "리더보드에서 경쟁하여 카운트다운 종료 시 상품 획득",
    continueAsGuest: "게스트로 계속하기",
    getStarted: "시작하기",
    of: "의",
    page: "페이지",
    viewYourPosition: "위치 보기",
    mint: "제조",
    limitFailed: '지정가 주문 실패',
    sendingTransaction: '거래 전송 중',

  },
  ES: {
    trade: 'Operar',
    connectWallet: 'Conectar Billetera',
    swap: 'Swap',
    send: 'Enviar',
    to: 'A',
    limit: 'Lim.',
    pay: 'Pagar',
    receive: 'Recibir',
    balance: 'Saldo:',
    settings: 'Ajustes',
    max: 'Máx.',
    enterAmount: 'Ingresa un monto',
    insufficient: 'Insuf.',
    swapSubtitle: 'Compra y venta de cualquier token',
    limitSubtitle: 'Opera a un precio específico',
    sendSubtitle: 'Transfiere tokens a cualquiera',
    docs: 'Docs',
    earn: 'Ganar',
    referrals: 'Referidos',
    portfolio: 'Portafolio',
    languages: 'Idiomas',
    networks: 'Redes',
    averagePrice: 'Precio Prom.',
    priceImpact: 'Impacto',
    swapFee: 'Comisión (0.02%)',
    limitFee: 'Comisión (0.00%)',
    isWorth: 'vale',
    When: 'Cuando',
    enterRecipient: 'Ingresa destinatario',
    enterWalletAddress: 'Ingresa dirección de billetera',
    market: 'Mercado',
    Warning: 'Advertencia: ¡Alto impacto de precio! Tu operación moverá el precio en más del 5%',
    markets: 'Mercados',
    type: 'Tipo',
    size: 'Tamaño',
    price: 'Precio',
    amountFilled: 'Cant. Ejecutada',
    active: 'Act.',
    time: 'Hora',
    view: 'Ver',
    amount: 'Monto',
    all: 'Todo',
    buy: 'Comprar',
    sell: 'Vender',
    noOpenOrders: 'No hay órdenes activas',
    noTradeHistory: 'Sin hist. de operaciones',
    noOrderHistory: 'Sin hist. de órdenes',
    cancelAll: 'Cancelar Todo',
    openOrders: 'Órdenes Activas',
    tradeHistory: 'Hist. Operac.',
    orderHistory: 'Hist. Órdenes',
    no: 'No',
    yes: 'Sí',
    total: 'Total',
    Spread: 'Spread',
    orderbook: 'Libro de Órdenes',
    trades: 'Operac.',
    availableLiquidity: 'Liquidez Disp.',
    dayVolume: 'Vol. 24h',
    dayHigh: 'Alto 24h',
    dayLow: 'Bajo 24h',
    dayChange: 'Cambia 24h',
    selectAToken: 'Selecciona un Token',
    selectTokenSubtitle: 'Elige de la lista o búscalo por símbolo o dirección.',
    searchToken: 'Buscar por símbolo o dirección',
    slippage: 'Slippage Máx.',
    partialFill: 'Relleno Parcial',
    assets: 'Activos',
    USDvalue: 'Valor USD',
    noWallet: '¿Sin billetera?',
    createWallet: ' Crear una',
    totalAccountValue: 'Valor Total de Cuenta',
    totalVolume: 'Vol. 24h',
    tradeValue: 'Valor de Operac.',
    filled: 'Ejecutado',
    canceled: 'Cancelado',
    status: 'Estado',
    mid: 'Med.',
    placeOrder: 'Realizar Orden',
    avgPrice: 'Precio Prom.',
    connectWalletSubtitle: 'Conecta tu billetera para comenzar a operar.',
    success: 'Éxito',
    viewOnExplorer: 'Ver en Explorer',
    online: 'Online',
    offline: 'Offline',
    twitter: 'Twitter',
    discord: 'Discord',
    beta: 'Beta',
    installed: 'Instalado',
    popular: 'Popular',
    chart: 'Gráfico',
    copied: 'Copiado',
    copyTokenAddress: 'Copiar dirección del token',
    clickCopyAddress: 'Clic para copiar',
    visitTokenWebsite: 'Visitar sitio del token',
    copy: 'Copiar',
    actions: 'Acciones',
    graphConnectWallet: 'Conecta tu billetera para ver tu portafolio.',
    noTokensDetected: 'No se detectaron tokens',
    performance: 'Rendimiento',
    balances: 'Saldos',
    welcome: 'Bienvenido',
    portfolioValue: 'Valor del Portafolio',
    approve: 'Aprobar',
    wrap: 'Wrap',
    unwrap: 'Unwrap',
    useMarket: 'Usar Mercado',
    onlyCurrentMarket: 'Solo este mercado',
    limitSettings: 'Ajustes de Límite',
    swapSettings: 'Ajustes de Swap',
    left: 'Izq.',
    right: 'Der.',
    customizableSubtitle: 'Personaliza tu experiencia de trading.',
    tradePanelPosition: 'Posición del Panel',
    orderbookPosition: 'Posición del Libro',
    side: 'Lado',
    panel: 'Panel',
    revertToDefault: 'Revertir a Default',
    language: 'Idioma',
    referralSettings: 'Ajustes de Referidos',
    changeusedref: 'Cambiar Ref. Usado',
    setRef: 'Establecer Ref.',
    createOrViewRefLink: 'Crear o Ver Link de Ref.',
    yourreflink: 'Tu Link de Ref.',
    copyLink: 'Copiar Link',
    earnings: 'Ganancias',
    totalfees: 'Total Comisiones',
    nothingtoclaim: 'Nada que reclamar',
    claimfees: 'Reclamar Comisiones',
    simpleView: 'Vista Simple',
    amountFilledSubtitle: 'Cant. de tokens ejecutados en esta orden',
    tradeValueSubtitle: 'Valor total de tu operación',
    statusSubtitle: 'Estado de ejecución de la orden',
    signTransaction: 'Firmar Transacción',
    addLiquidityOnly: 'Solo Agregar Liquidez',
    addLiquidityOnlySubtitle: 'Si activo, la orden se agregará como maker',
    claimTitle: 'Reclama Tus Ganancias',
    totalClaim: 'Total Reclamable',
    shareEarn: 'Comparte y Gana',
    customize: 'Personalizar',
    create: 'Crear',
    noLink: 'Crea un link de ref. para comenzar a ganar!',
    communityRewards: 'Recompensas Comunitarias',
    communityRewardsText: 'Gana 25% de comisión y ofrece 25% de descuento a tus referidos',
    instantTracking: 'Seguimiento Instantáneo',
    instantTrackingText: 'Las ganancias se pueden reclamar al instante',
    tierBenefits: 'Multiplicadores',
    tierBenefitsText: 'Tú y tus referidos ganarán más recompensas',
    usingCode: 'Usando Código:',
    enteracode: 'Ingresa el código de ref.',
    earningsDashboard: 'Dashboard de Ganancias',
    earningsSubtitle: 'Monitorea y reclama tus recompensas',
    totalClaimable: 'Total Reclamable',
    tokenBreakdown: 'Desglose de Token',
    availableToClaim: 'Disponible para reclamar',
    referralsHelp: 'Reclama las comisiones del programa; se recogen en el token de pago y se pueden reclamar cuando quieras.',
    learnMore: 'Más Información',
    noSelfRefer: 'No puedes usar tu propio código de ref.',
    customizeWarning: 'Cambiar tu link hará que el anterior deje de funcionar.',
    createWarning: 'Crea un link de ref. personalizado',
    referralSubtitle: '¡Usa el código de un amigo o creador y obtén 25% de descuento!',
    yourLink: 'Tu Link:',
    createCode: 'Crear Código',
    signTxn: 'Firmar Txn',
    getHelp: 'Obtener Ayuda',
    totalVol: 'Vol. Total',
    activeOrders: 'Órdenes Activas',
    details: 'Detalles',
    account: 'CUENTA',
    accountSubtitle: 'Resumen reciente de tu billetera',
    toggle: 'Alternar visibilidad de números',
    day: '24h',
    week: '1s',
    weektwo: '2s',
    month: '1m',
    past: 'Pasado',
    portValue: 'Valor Portaf.',
    slippageHelp: 'Máx. diferencia (%) entre precio esperado y ejecutado',
    averagePriceHelp: 'Precio promedio estimado',
    priceImpactHelp: 'Impacto estimado en el precio',
    nofeeforwrap: 'Wrap/Unwrap de ETH es 1:1 sin comisiones',
    takerfeeexplanation: 'Órdenes taker cobran 0.02%',
    makerfeeexplanation: 'Órdenes maker sin comisión',
    fee: 'Comisión',
    cancel: 'Cancelar',
    switchto: 'Cambiar a',
    insufficientLiquidity: 'Liquidez Insuf.',
    insufficientLiquidityWarning: 'Advertencia: Liquidez insuf. Divide la orden o activa relleno parcial',
    insufficientLiquidityWarningMultihop: 'Advertencia: Liquidez insuf. Divide la orden en partes',
    priceOutOfRangeBuy: 'Precio de compra fuera de rango',
    priceOutOfRangeSell: 'Precio de venta fuera de rango',
    clearRef: 'Limpiar código de ref.',
    comingSoon: 'Próximamente...',
    earnDesc: 'Trabajamos para ofrecerte nuevas formas de ganar con crypto. ¡Pronto más!',
    showOB: 'Mostrar Libro',
    showOC: 'Mostrar Centro de Órdenes',
    priceOutOfRangeWarningBuy: 'Advertencia: Límite mayor que el mínimo de venta. Puede ejecutarse como taker',
    priceOutOfRangeWarningSell: 'Advertencia: Límite menor que el máximo de compra. Puede ejecutarse como taker',
    limitPrice: 'Precio Límite',
    limitPriceSubtitle: 'Precio de ejecución de la orden',
    partialFillSubtitle: 'Si activo, permite ejecución parcial ante exceso de slippage',
    sHigh: 'Máx. Sesión',
    sLow: 'Mín. Sesión',
    hideBalances: 'Ocultar Saldos',
    disconnect: 'Desconectar',
    tradingStats: 'Estadísticas',
    refStats: 'Estadísticas Ref.',
    claimableRewards: 'Recompensas Recl.',
    myCode: 'Mi Código:',
    noCode: '¿Sin código? Crea uno',
    bal: 'Saldo',
    landing: 'Sitio',
    terms: 'Términos',
    view_documentation: 'Conoce Crystal',
    visit_homepage: 'Visita el sitio de Crystal',
    read_terms: 'Términos legales',
    join_community: 'Únete a la comunidad Crystal',
    follow_updates: 'Sigue las actualizaciones de Crystal',
    more: 'Más',
    onlyCurrentMarketHelp: 'Mostrar solo órdenes de este mercado',
    swapComplete: 'Swap Completo',
    limitComplete: 'Orden Límite Completa',
    sendComplete: 'Envío Completo',
    limitCancelled: 'Orden Límite Cancelada',
    fillComplete: 'Orden Ejecutada',
    wrapComplete: 'Wrap Completo',
    unwrapComplete: 'Unwrap Completo',
    approveComplete: 'Aprobación Completa',
    basic: 'BÁS.',
    pro: 'PRO',
    searchMarkets: 'Buscar Mercados',
    clear: 'Limpiar',
    volume: 'Vol.',
    byConnecting: 'Al conectar, aceptas los',
    termsOfService: 'Términos',
    andConsentTo: 'y das tu consentimiento a',
    privacyPolicy: 'Privacidad',
    enterReferralCode: 'Ingresa código de ref.',
    setReferral: 'Establecer Ref.',
    clearReferralLink: 'Limpiar código',
    codeTaken: 'Código en uso',
    invalid: 'Inválido',
    requestingConnection: 'Solicitando conexión',
    confirmConnection1: 'Confirma la conexión en',
    confirmConnection2: 'la extensión para continuar',
    lessThanMinSize: 'El tamaño debe ser >1 USDC',
    enterLimitPrice: 'Ingresa precio límite',
    advancedView: 'Vista Avanzada',
    basicView: 'Vista Básica',
    advancedViewText: 'Domina el mercado',
    basicViewText: 'Opera con facilidad',
    noTokens: 'No se encontraron tokens',
    noMarkets: 'No se encontraron mercados',
    toNavigate: 'navegar',
    toSelect: 'seleccionar',
    toClose: 'cerrar',
    pleaseEnterCode: 'Ingresa un código de ref.',
    transactionHistory: 'Histórico de Transacciones',
    search: 'Buscar',
    minimumSize: 'Tamaño Mínimo',
    enableFilter: 'Activar Filtro',
    noTransactionsYet: 'Aún no hay transacciones',
    filledAt: 'ejecutado a',
    start: 'Inicio',
    end: 'Fin',
    skew: 'Sesgo',
    orders: 'Órdenes',
    enterStartPrice: 'Ingresa precio inicial',
    enterEndPrice: 'Ingresa precio final',
    startPriceHigh: 'Precio inicial muy alto',
    startPriceLow: 'Precio inicial muy bajo',
    endPriceHigh: 'Precio final muy alto',
    endPriceLow: 'Precio final muy bajo',
    scaleMinSize: 'El tamaño mínimo debe ser >1 USDC',
    enterOrders: 'Ingresa cantidad de órdenes',
    enterSkew: 'Ingresa sesgo de tamaño',
    transactionDetails: 'Detalles de Transacción',
    swapDetails: 'Detalles de Swap',
    limitOrderDetails: 'Detalles de Orden Límite',
    sendDetails: 'Detalles de Envío',
    cancelDetails: 'Detalles de Cancelación',
    fillDetails: 'Detalles de Ejecución',
    wrapDetails: 'Detalles de Wrap',
    unwrapDetails: 'Detalles de Unwrap',
    approveDetails: 'Detalles de Aprobación',
    generalInfo: 'Información General',
    txType: 'Tipo de Transacción',
    txTime: 'Tiempo de Transacción',
    txHash: 'Hash de Transacción',
    tokenInfo: 'Información de Token',
    fromToken: 'Token Origen',
    toToken: 'Token Destino',
    recipientInfo: 'Información del Destinatario',
    contractInfo: 'Información del Contrato',
    address: 'Dirección',
    token: 'Token',
    feeInfo: 'Información de Comisiones',
    gasUsed: 'Gas Utilizado',
    gasPrice: 'Precio del Gas',
    totalFee: 'Comisión Total',
    back: 'Volver',
    at: 'a',
    leaderboard: 'Leaderboard',
    scale: 'Escala',
    orderType: 'Tipo de Orden',
    editAccountTitle: "Editar Cuenta",
    editAccountSubtitle: "Cambia tu nombre de usuario y foto de perfil",
    username: "Nombre de Usuario",
    chooseNewPhoto: "Elegir Nueva Foto",
    saveChanges: "Guardar Cambios",
    viewRules: "Ver Reglas",
    xpEarned: "XP Ganado",
    rank: "Rango",
    editAccount: "Editar Cuenta",
    createAccount: "Crear Cuenta",
    user: "Usuario",
    totalXP: "XP Total",
    choosePhoto: "Elegir Foto",
    next: "Siguiente",
    skip: "Omitir",
    complete: "Completar",
    challengeOverview: "Resumen del Desafío",
    learnHowToCompete: "Aprende cómo competir y ganar recompensas",
    precisionMatters: "La Precisión Importa",
    placeYourBids: "Coloca tus ofertas hacia el punto medio para ganar puntos extra",
    earnXp: "Gana XP",
    midsGiveYou: "Los puntos medios te dan XP que contribuye a tu clasificación general",
    claimRewards: "Reclamar Recompensas",
    competeOnLeaderboards: "Compite en las tablas de clasificación para ganar premios cuando termine la cuenta atrás",
    continueAsGuest: "Continuar como Invitado",
    getStarted: "Comenzar",
    of: 'de',
    page: 'Página',
    viewYourPosition: "Ver tu posición",
    mint: "Mint",
    limitFailed: 'Orden Límite Fallida',
    sendingTransaction: 'Sending Transaction',
  }
};

type LanguageContextType = {
  language: string;
  availablelanguages: any;
  setLanguage: (lang: string) => void;
  t: (key: string) => string;
};

const LanguageContext = createContext<LanguageContextType>({
  language: 'EN',
  availablelanguages: Object.keys(translations),
  setLanguage: () => {},
  t: (key: string) => key,
});

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({
  children,
}) => {
  const [language, setLanguage] = useState(() => {
    const savedLanguage = localStorage.getItem('crystal_language');
    return savedLanguage || 'EN';
  });
  const availablelanguages = Object.keys(translations);

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider
      value={{ language, availablelanguages, setLanguage, t }}
    >
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
